// src/lib/components/admin/TagInput.svelte
<script lang="ts">
	let {
		tags = $bindable<string[]>([]),
		placeholder = 'Add a tag...',
		disabled = false,
	}: {
		tags?: string[];
		placeholder?: string;
		disabled?: boolean;
	} = $props();

	let input = $state('');

	function addTag() {
		const value = input.trim();
		if (value && !tags.includes(value)) {
			tags = [...tags, value];
		}
		input = '';
	}

	function removeTag(tag: string) {
		tags = tags.filter((t) => t !== tag);
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter' || e.key === ',') {
			e.preventDefault();
			addTag();
		}
		if (e.key === 'Backspace' && !input && tags.length > 0) {
			tags = tags.slice(0, -1);
		}
	}
</script>

<div class="chip-input-wrap" class:disabled>
	{#each tags as tag (tag)}
		<span class="chip">
			{tag}
			{#if !disabled}
				<button class="chip-remove" type="button" onclick={() => removeTag(tag)} aria-label="Remove {tag}">&times;</button>
			{/if}
		</span>
	{/each}
	{#if !disabled}
		<input
			type="text"
			class="chip-text-input"
			bind:value={input}
			onkeydown={handleKeydown}
			onblur={addTag}
			{placeholder}
		/>
	{/if}
</div>

// apps/admin/src/components/TagInput.tsx
import type { Component } from 'solid-js';
import { For, createSignal } from 'solid-js';
import './ChipInput.css';

type TagInputProps = {
	tags: string[];
	onChange: (tags: string[]) => void;
	placeholder?: string;
	disabled?: boolean;
	validate?: (value: string) => boolean;
};

export const TagInput: Component<TagInputProps> = (props) => {
	const [input, setInput] = createSignal('');

	function addTag(value: string) {
		const trimmed = value.trim().replace(/,+$/, '').trim();
		if (trimmed && !props.tags.includes(trimmed) && (props.validate?.(trimmed) ?? true)) {
			props.onChange([...props.tags, trimmed]);
		}
		setInput('');
	}

	function removeTag(tag: string) {
		props.onChange(props.tags.filter((t) => t !== tag));
	}

	function handleKeyDown(e: KeyboardEvent & { currentTarget: HTMLInputElement }) {
		if (e.key === 'Enter' || e.key === ',') {
			e.preventDefault();
			addTag(e.currentTarget.value);
		} else if (e.key === 'Backspace' && !e.currentTarget.value && props.tags.length > 0) {
			removeTag(props.tags[props.tags.length - 1]!);
		}
	}

	return (
		<div class={`chip-input-wrap${props.disabled ? ' disabled' : ''}`}>
			<For each={props.tags}>
				{(tag) => (
					<span class="chip">
						{tag}
						<button type="button" class="chip-remove" onClick={() => removeTag(tag)} disabled={props.disabled} aria-label={`Remove ${tag}`}>
							×
						</button>
					</span>
				)}
			</For>
			<input
				class="chip-text-input"
				type="text"
				value={input()}
				onInput={(e) => setInput(e.currentTarget.value)}
				onKeyDown={handleKeyDown}
				onBlur={(e) => {
					if (e.currentTarget.value) addTag(e.currentTarget.value);
				}}
				placeholder={props.tags.length === 0 ? (props.placeholder ?? 'Add tag…') : ''}
				disabled={props.disabled}
			/>
		</div>
	);
};
