// apps/admin/src/routes/admin/(app)/emails/subscribers/index.tsx
import { createAsync, revalidate, type RouteDefinition } from '@solidjs/router';
import { For, Show, createMemo, createSignal } from 'solid-js';
import { createSolidTable, getCoreRowModel, getFilteredRowModel, getFacetedRowModel, getFacetedUniqueValues, getSortedRowModel, createColumnHelper, type SortingState, type ColumnFiltersState } from '@tanstack/solid-table';
import { toast } from 'solid-sonner';
import {
	Badge, Button, AlertDialog, DataTable, PageHeader,
	createSelectColumn, multiSelectFilter, type RowSelectionState,
} from '~/components';
import { requireSession } from '~/routes/admin/session';
import { can } from '~/lib/can';
import { subscriberStatusVariant, toastError } from '~/lib/utils';
import { listSubscribers, deleteSubscribers, blocklistSubscribers } from '../subscribers.server';
import { listLists } from '../lists.server';
import { SubscriberEditor } from './SubscriberEditor';
import './index.css';

export const route: RouteDefinition = {
	preload: () => {
		void listSubscribers();
		void listLists();
	},
};

type SubscriberList = {
	id: number;
	name: string;
	subscription_status: string;
};

type ListmonkSubscriber = {
	id: number;
	email: string;
	name: string;
	status: string;
	lists: SubscriberList[];
	created_at: string;
	updated_at: string;
};

const columnHelper = createColumnHelper<ListmonkSubscriber>();

export default function SubscribersPage() {
	const session = createAsync(() => requireSession());
	const data = createAsync(() => listSubscribers());
	const listsData = createAsync(() => listLists());

	// ─── State ───────────────────────────────────────────────────────────────────

	const [globalFilter, setGlobalFilter] = createSignal('');
	const [columnFilters, setColumnFilters] = createSignal<ColumnFiltersState>([]);
	const [rowSelection, setRowSelection] = createSignal<RowSelectionState>({});
	const [sorting, setSorting] = createSignal<SortingState>([]);

	const [editorOpen, setEditorOpen] = createSignal(false);
	const [editorSubscriber, setEditorSubscriber] = createSignal<ListmonkSubscriber | null>(null);

	const [confirmDelete, setConfirmDelete] = createSignal(false);
	const [confirmBlocklist, setConfirmBlocklist] = createSignal(false);

	// ─── Handlers ─────────────────────────────────────────────────────────────────

	function openCreate() {
		setEditorSubscriber(null);
		setEditorOpen(true);
	}

	function openEdit(sub: ListmonkSubscriber) {
		setEditorSubscriber(sub);
		setEditorOpen(true);
	}

	async function handleEditorSaved() {
		setRowSelection({});
		await revalidate('listSubscribers');
	}

	async function handleDelete() {
		try {
			await deleteSubscribers(selectedRows().map((s) => s.id));
			toast.success(`${selectedRows().length} subscriber${selectedRows().length > 1 ? 's' : ''} deleted.`);
			setRowSelection({});
			await revalidate('listSubscribers');
		} catch (err) {
			toastError(err, 'Failed to delete subscribers.');
		}
	}

	async function handleBlocklist() {
		try {
			await blocklistSubscribers(selectedRows().map((s) => s.id));
			toast.success(`${selectedRows().length} subscriber${selectedRows().length > 1 ? 's' : ''} blocklisted.`);
			setRowSelection({});
			await revalidate('listSubscribers');
		} catch (err) {
			toastError(err, 'Failed to blocklist subscribers.');
		}
	}

	// ─── Columns ─────────────────────────────────────────────────────────────────

	const columns = [
		createSelectColumn<ListmonkSubscriber>(),
		columnHelper.accessor('email', {
			header: 'Email',
			enableColumnFilter: false,
			cell: (info) => (
				<button class="cell-link" onClick={() => openEdit(info.row.original)}>{info.getValue()}</button>
			),
		}),
		columnHelper.accessor('name', {
			header: 'Name',
			enableColumnFilter: false,
			cell: (info) => info.getValue() || '—',
		}),
		columnHelper.accessor('status', {
			header: 'Status',
			filterFn: multiSelectFilter,
			cell: (info) => <Badge variant={subscriberStatusVariant(info.getValue())}>{info.getValue()}</Badge>,
		}),
		columnHelper.accessor('lists', {
			header: 'Lists',
			enableSorting: false,
			enableColumnFilter: false,
			cell: (info) => {
				const lists = info.getValue();
				return lists.length === 0
					? <span class="cell-muted">—</span>
					: (
						<div class="cell-badges">
							<For each={lists}>
								{(list) => (
									<Badge variant={list.subscription_status === 'unconfirmed' ? 'warning' : 'default'}>
										{list.name}{list.subscription_status === 'unconfirmed' ? ' (unconfirmed)' : ''}
									</Badge>
								)}
							</For>
						</div>
					);
			},
		}),
		columnHelper.accessor('created_at', {
			header: 'Created',
			enableColumnFilter: false,
			cell: (info) => <span class="cell-date">{new Date(info.getValue()).toLocaleDateString()}</span>,
		}),
		columnHelper.accessor('updated_at', {
			header: 'Updated',
			enableColumnFilter: false,
			cell: (info) => <span class="cell-date">{new Date(info.getValue()).toLocaleDateString()}</span>,
		}),
	];

	// ─── Table ───────────────────────────────────────────────────────────────────

	const table = createSolidTable({
		get data() { return (data()?.subscribers ?? []) as ListmonkSubscriber[]; },
		columns,
		state: {
			get globalFilter() { return globalFilter(); },
			get columnFilters() { return columnFilters(); },
			get rowSelection() { return rowSelection(); },
			get sorting() { return sorting(); },
		},
		onGlobalFilterChange: setGlobalFilter,
		onColumnFiltersChange: setColumnFilters,
		onRowSelectionChange: setRowSelection,
		onSortingChange: setSorting,
		enableRowSelection: () => can(session(), 'subscriber', 'delete'),
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getFacetedRowModel: getFacetedRowModel(),
		getFacetedUniqueValues: getFacetedUniqueValues(),
		getSortedRowModel: getSortedRowModel(),
	});

	const selectedRows = createMemo(() => table.getSelectedRowModel().rows.map((r) => r.original));

	const canBlocklist = createMemo(() =>
		can(session(), 'subscriber', 'blocklist') &&
		selectedRows().some((s) => s.status !== 'blocklisted'),
	);

	// ─── Toolbar ──────────────────────────────────────────────────────────────────

	const toolbar = () => (
		<Show
			when={selectedRows().length > 0 && can(session(), 'subscriber', 'delete')}
			fallback={
				<div class="dt-toolbar-search">
					<input
						class="admin-input"
						type="text"
						placeholder="Filter by email or name…"
						value={globalFilter()}
						onInput={(e) => setGlobalFilter(e.currentTarget.value)}
					/>
					<Show when={can(session(), 'subscriber', 'create')}>
						<Button onClick={openCreate}>+ New Subscriber</Button>
					</Show>
				</div>
			}
		>
			<span class="dt-selection-count">{selectedRows().length} selected</span>
			<Show when={canBlocklist()}>
				<Button variant="danger-outline" onClick={() => setConfirmBlocklist(true)}>Blocklist</Button>
			</Show>
			<Button variant="danger-outline" onClick={() => setConfirmDelete(true)}>Delete</Button>
			<button class="dt-clear-btn" onClick={() => setRowSelection({})}>Clear</button>
		</Show>
	);

	return (
		<>
			<PageHeader title="Subscribers" />

			<DataTable table={table} toolbar={toolbar} emptyMessage="No subscribers found." />

			<AlertDialog
				open={confirmDelete()}
				onOpenChange={setConfirmDelete}
				title={`Delete Subscriber${selectedRows().length > 1 ? 's' : ''}`}
				description={`Permanently delete ${selectedRows().length} subscriber${selectedRows().length > 1 ? 's' : ''}? This cannot be undone.`}
				confirmLabel="Yes, delete"
				onconfirm={handleDelete}
			/>

			<AlertDialog
				open={confirmBlocklist()}
				onOpenChange={setConfirmBlocklist}
				title={`Blocklist Subscriber${selectedRows().length > 1 ? 's' : ''}`}
				description={`Blocklist ${selectedRows().length} subscriber${selectedRows().length > 1 ? 's' : ''}? They will no longer receive any emails.`}
				confirmLabel="Yes, blocklist"
				onconfirm={handleBlocklist}
			/>

			<SubscriberEditor
				open={editorOpen()}
				onOpenChange={setEditorOpen}
				subscriber={editorSubscriber()}
				allLists={listsData()?.lists ?? []}
				canEdit={can(session(), 'subscriber', 'edit')}
				onSaved={handleEditorSaved}
			/>
		</>
	);
}

// src/routes/admin/emails/subscribers/+page.svelte
<script lang="ts">
	import { Badge, Button, ConfirmDialog, EmptyState, Input, DataTable } from '$lib/components/admin';
	import SubscriberEditor from './components/SubscriberEditor.svelte';
	import { createSvelteTable, renderSnippet, multiSelectFilter, createSelectColumn } from '$lib/components/admin';
	import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getFacetedRowModel, getFacetedUniqueValues, type RowSelectionState, type ColumnFiltersState } from '@tanstack/table-core';
	import { toast } from 'svelte-sonner';
	import { toastError } from '$lib/utils/toast-error';
	import { listSubscribers, deleteSubscribers, blocklistSubscribers } from '../subscribers.remote';
	import { subscriberStatusVariant } from '$lib/utils/admin';
	import type { ListmonkSubscriber } from '$lib/server/listmonk';
	import { listLists } from '../lists.remote';
	import { getSession } from '../../session.remote';
	import { can } from '../../can';

	let [session, data, listsData] = $derived(await Promise.all([getSession(), listSubscribers(), listLists()]));

	let globalFilter = $state('');
	let columnFilters = $state<ColumnFiltersState>([]);

	// Row selection
	let rowSelection = $state<RowSelectionState>({});
	let selectedRows = $derived.by(() => {
		if (!data) return [];
		return Object.keys(rowSelection)
			.filter((k) => rowSelection[k])
			.map((k) => data.subscribers[Number(k)])
			.filter(Boolean);
	});
	let selectedCount = $derived(selectedRows.length);

	function clearSelection() {
		rowSelection = {};
	}

	// Subscriber editor (create + edit)
	let editorOpen = $state(false);
	let editorSubscriber = $state<ListmonkSubscriber | null>(null);

	// Confirm dialogs
	let confirmDelete = $state(false);
	let confirmBlocklist = $state(false);

	function openCreate() {
		editorSubscriber = null;
		editorOpen = true;
	}

	function openEdit(sub: ListmonkSubscriber) {
		editorSubscriber = sub;
		editorOpen = true;
	}

	function handleEditorSaved() {
		clearSelection();
		refreshList();
	}

	async function handleDelete() {
		try {
			await deleteSubscribers(selectedRows.map((sub) => sub.id));
			toast.success(`${selectedCount} subscriber${selectedCount > 1 ? 's' : ''} deleted.`);
			clearSelection();
			refreshList();
		} catch (err) {
			toastError(err, 'Failed to delete subscriber.');
		}
	}

	async function handleBlocklist() {
		try {
			await blocklistSubscribers(selectedRows.map((sub) => sub.id));
			toast.success(`${selectedCount} subscriber${selectedCount > 1 ? 's' : ''} blocklisted.`);
			clearSelection();
			refreshList();
		} catch (err) {
			toastError(err, 'Failed to blocklist subscriber.');
		}
	}

	function refreshList() {
		listSubscribers().refresh();
	}

	let canBlocklist = $derived(
		can(session, 'subscriber', 'blocklist') && selectedRows.some((s) => s.status !== 'blocklisted'),
	);

	const columnHelper = createColumnHelper<ListmonkSubscriber>();

	const columns = [
		createSelectColumn<ListmonkSubscriber>(),
		columnHelper.accessor('email', {
			header: 'Email',
			cell: (info) => renderSnippet(emailCell, info.row.original),
			enableColumnFilter: false,
		}),
		columnHelper.accessor('name', {
			header: 'Name',
			cell: (info) => info.getValue() || '—',
			enableColumnFilter: false,
		}),
		columnHelper.accessor('status', {
			header: 'Status',
			cell: (info) => renderSnippet(statusCell, info.getValue()),
			enableColumnFilter: true,
			filterFn: multiSelectFilter,
		}),
		columnHelper.accessor(
			(row) => row.lists.map((l) => l.subscription_status === 'unconfirmed' ? `${l.name} (unconfirmed)` : l.name),
			{
				id: 'lists',
				header: 'Lists',
				cell: (info) => renderSnippet(listsCell, info.row.original.lists),
				enableSorting: false,
				enableColumnFilter: true,
				filterFn: (row, columnId, filterValue: unknown[]) => {
					if (!filterValue || filterValue.length === 0) return true;
					const values: string[] = row.getValue(columnId);
					return values.some((v) => filterValue.includes(v));
				},
				getUniqueValues: (row) =>
					row.lists.map((l) => l.subscription_status === 'unconfirmed' ? `${l.name} (unconfirmed)` : l.name),
			},
		),
		columnHelper.accessor('created_at', {
			header: 'Created',
			cell: (info) => renderSnippet(dateCell, info.getValue()),
			enableColumnFilter: false,
		}),
		columnHelper.accessor('updated_at', {
			header: 'Updated',
			cell: (info) => renderSnippet(dateCell, info.getValue()),
			enableColumnFilter: false,
		}),
	];
</script>

{#snippet emailCell(sub: ListmonkSubscriber)}
	<button class="cell-link" onclick={() => openEdit(sub)}>{sub.email}</button>
{/snippet}

{#snippet statusCell(status: string)}
	<Badge variant={subscriberStatusVariant(status)}>{status}</Badge>
{/snippet}

{#snippet listsCell(lists: { id: number; name: string; subscription_status: string }[])}
	<div class="cell-badges">
		{#each lists as list}
			<Badge variant={list.subscription_status === 'unconfirmed' ? 'warning' : 'default'}>
				{list.name}{#if list.subscription_status === 'unconfirmed'} (unconfirmed){/if}
			</Badge>
		{/each}
		{#if lists.length === 0}
			<span class="cell-muted">—</span>
		{/if}
	</div>
{/snippet}

{#snippet dateCell(date: string)}
	<span class="cell-date">{new Date(date).toLocaleDateString()}</span>
{/snippet}

<h1>Subscribers</h1>

{#if data}
	{#snippet toolbar()}
		{#if selectedCount > 0 && can(session, 'subscriber', 'delete')}
			<span class="toolbar-count">{selectedCount} selected</span>
			<div class="toolbar-actions">
				{#if canBlocklist}
					<Button variant="danger-outline" onclick={() => (confirmBlocklist = true)}>Blocklist</Button>
				{/if}
				<Button variant="danger-outline" onclick={() => (confirmDelete = true)}>Delete</Button>
				<button class="toolbar-clear" onclick={clearSelection}>Clear</button>
			</div>
		{:else}
			<div class="toolbar-search">
				<Input type="text" placeholder="Filter by email or name..." bind:value={globalFilter} />
			</div>
			{#if can(session, 'subscriber', 'create')}
				<Button variant="primary" onclick={openCreate}>+ New Subscriber</Button>
			{/if}
		{/if}
	{/snippet}

	{@const table = createSvelteTable({
		data: data.subscribers,
		columns,
		state: { rowSelection, columnFilters, globalFilter },
		onRowSelectionChange: (updater) => {
			rowSelection = typeof updater === 'function' ? updater(rowSelection) : updater;
		},
		onColumnFiltersChange: (updater) => {
			columnFilters = typeof updater === 'function' ? updater(columnFilters) : updater;
		},
		onGlobalFilterChange: (updater) => {
			globalFilter = typeof updater === 'function' ? updater(globalFilter) : updater;
		},
		enableColumnFilters: true,
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getFacetedRowModel: getFacetedRowModel(),
		getFacetedUniqueValues: getFacetedUniqueValues(),
	})}
	<DataTable {table} {toolbar} pageSize={20} />
	{#if data.subscribers.length === 0}
		<EmptyState message="No subscribers found." />
	{/if}
{/if}

<ConfirmDialog
	bind:open={confirmDelete}
	title="Delete Subscriber{selectedCount > 1 ? 's' : ''}"
	description="Permanently delete {selectedCount} subscriber{selectedCount > 1 ? 's' : ''}? This cannot be undone."
	confirmLabel="Yes, delete"
	onconfirm={handleDelete}
/>

<ConfirmDialog
	bind:open={confirmBlocklist}
	title="Blocklist Subscriber{selectedCount > 1 ? 's' : ''}"
	description="Blocklist {selectedCount} subscriber{selectedCount > 1 ? 's' : ''}? They will no longer receive any emails."
	confirmLabel="Yes, blocklist"
	onconfirm={handleBlocklist}
/>

<SubscriberEditor
	bind:open={editorOpen}
	subscriber={editorSubscriber}
	allLists={listsData?.lists ?? []}
	canEdit={can(session, 'subscriber', 'edit')}
	onSaved={handleEditorSaved}
/>
