// apps/admin/src/routes/(auth)/reset-password.tsx
import { createSignal, Show } from 'solid-js';
import { useNavigate, useSearchParams } from '@solidjs/router';
import { toast } from 'solid-sonner';
import { authClient } from '~/lib/auth-client';
import { LOGO_FILL_ORANGE } from '~/lib/constants';
import { FormField, Input, Button, Logo } from '~/components';
import './auth.css';

export default function ResetPasswordPage() {
	const navigate = useNavigate();
	const [searchParams] = useSearchParams<{ token?: string }>();
	const [newPassword, setNewPassword] = createSignal('');
	const [confirmPassword, setConfirmPassword] = createSignal('');
	const [error, setError] = createSignal('');
	const [loading, setLoading] = createSignal(false);

	const token = () => searchParams.token ?? '';

	async function handleSubmit(e: SubmitEvent) {
		e.preventDefault();
		setError('');

		if (newPassword() !== confirmPassword()) {
			setError('Passwords do not match');
			return;
		}

		if (newPassword().length < 8) {
			setError('Password must be at least 8 characters');
			return;
		}

		setLoading(true);

		try {
			const result = await authClient.resetPassword({
				newPassword: newPassword(),
				token: token(),
			});

			if (result.error) {
				setError(result.error.message ?? 'Failed to reset password');
				return;
			}

			toast.success('Password reset successfully. Please sign in.');
			navigate('/login');
		} catch {
			setError('Failed to reset password. The link may have expired.');
		} finally {
			setLoading(false);
		}
	}

	return (
		<div class="auth-page">
			<div class="auth-container">
				<Logo fill={LOGO_FILL_ORANGE} height={140} />

				<Show
					when={token()}
					fallback={
						<div class="auth-card">
							<h2>Invalid reset link</h2>
							<p class="auth-muted">This password reset link is invalid or has expired.</p>
							<a href="/forgot-password" class="auth-link">Request a new one</a>
						</div>
					}
				>
					<form class="auth-card" onSubmit={handleSubmit}>
						<h2>Set new password</h2>

						<FormField label="New password">
							<Input
								type="password"
								value={newPassword()}
								onInput={(e) => setNewPassword(e.currentTarget.value)}
								required
								minLength={8}
							/>
						</FormField>

						<FormField label="Confirm password">
							<Input
								type="password"
								value={confirmPassword()}
								onInput={(e) => setConfirmPassword(e.currentTarget.value)}
								required
								minLength={8}
							/>
						</FormField>

						<Show when={error()}>
							<p class="auth-error">{error()}</p>
						</Show>

						<Button type="submit" disabled={loading()} aria-busy={loading()}>
							{loading() ? 'Resetting…' : 'Reset password'}
						</Button>

						<a href="/login" class="auth-link">Back to login</a>
					</form>
				</Show>
			</div>
		</div>
	);
}

// src/routes/admin/reset-password/+page.svelte
<script lang="ts">
  import { authClient } from "$lib/auth-client";
  import { goto } from "$app/navigation";
  import { page } from "$app/state";
  import { toast } from "svelte-sonner";
  import { FormField, Input, Button, Logo } from "$lib/components/admin";

  let newPassword = $state("");
  let confirmPassword = $state("");
  let error = $state("");
  let loading = $state(false);

  let token = $derived(page.url.searchParams.get("token") ?? "");

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = "";

    if (newPassword !== confirmPassword) {
      error = "Passwords do not match";
      return;
    }

    if (newPassword.length < 8) {
      error = "Password must be at least 8 characters";
      return;
    }

    loading = true;

    try {
      const result = await authClient.resetPassword({
        newPassword,
        token,
      });

      if (result.error) {
        error = result.error.message ?? "Failed to reset password";
        return;
      }

      toast.success("Password reset successfully. Please sign in.");
      goto("/admin/login");
    } catch {
      error = "Failed to reset password. The link may have expired.";
    } finally {
      loading = false;
    }
  }
</script>

<div class="login-page">
  <div class="login-container">
    <Logo fill="#ff6f00" height={140} />

    {#if !token}
      <div class="success-card">
        <h2>Invalid reset link</h2>
        <p>This password reset link is invalid or has expired.</p>
        <a href="/admin/forgot-password" class="back-link">Request a new one</a>
      </div>
    {:else}
      <form onsubmit={handleSubmit}>
        <h2>Set new password</h2>

        <FormField label="New password">
          <Input type="password" bind:value={newPassword} required minlength={8} />
        </FormField>

        <FormField label="Confirm password">
          <Input type="password" bind:value={confirmPassword} required minlength={8} />
        </FormField>

        {#if error}
          <p class="error">{error}</p>
        {/if}

        <Button type="submit" disabled={loading} aria-busy={loading}>
          {loading ? "Resetting..." : "Reset password"}
        </Button>

        <a href="/admin/login" class="back-link">Back to login</a>
      </form>
    {/if}
  </div>
</div>

<style>
  .login-page {
    min-height: 100vh;
    background: var(--color-page-bg);
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .login-container {
    width: 100%;
    max-width: 400px;
    padding: 2rem;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .login-container :global(.logo) {
    margin-bottom: 2rem;
  }

  form, .success-card {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    background: var(--color-surface);
    padding: 2rem;
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-md);
    width: 100%;
  }

  h2 {
    margin: 0;
    font-size: 1.25rem;
    color: var(--color-foreground);
  }

  .error {
    color: var(--color-destructive);
    margin: 0;
    font-size: 0.9rem;
  }

  .back-link {
    text-align: center;
    color: var(--color-primary);
    font-size: 0.9rem;
    text-decoration: none;
  }

  .back-link:hover {
    text-decoration: underline;
  }
</style>
