// src/routes/admin/settings/email/components/GeneralTab.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import { Button, FormField, Input, Switch, Section, TagInput } from '$lib/components/admin';
	import { useForm } from '$lib/utils/use-form.svelte';
	import * as v from 'valibot';
	import type { ListmonkSettings } from '$lib/server/listmonk';

	let {
		settings,
		canEdit,
		onsave,
	}: {
		settings: ListmonkSettings;
		canEdit: boolean;
		onsave: (partial: Record<string, unknown>) => Promise<void>;
	} = $props();

	const schema = v.object({
		siteName: v.pipe(v.string(), v.nonEmpty('Site name is required')),
		rootUrl: v.pipe(v.string(), v.nonEmpty('Root URL is required'), v.url('Must be a valid URL')),
		logoUrl: v.string(),
		faviconUrl: v.string(),
		fromEmail: v.string(),
		notifyEmails: v.array(v.string()),
		sendOptinConfirmation: v.boolean(),
		enablePublicSubPage: v.boolean(),
		enablePublicArchive: v.boolean(),
		enablePublicArchiveRss: v.boolean(),
		checkUpdates: v.boolean(),
	});

	const form = useForm(untrack(() => ({
		siteName: settings['app.site_name'],
		rootUrl: settings['app.root_url'],
		logoUrl: settings['app.logo_url'] ?? '',
		faviconUrl: settings['app.favicon_url'] ?? '',
		fromEmail: settings['app.from_email'],
		notifyEmails: settings['app.notify_emails'] ?? [],
		sendOptinConfirmation: settings['app.send_optin_confirmation'],
		enablePublicSubPage: settings['app.enable_public_subscription_page'],
		enablePublicArchive: settings['app.enable_public_archive'],
		enablePublicArchiveRss: settings['app.enable_public_archive_rss_content'],
		checkUpdates: settings['app.check_updates'],
	})), schema);

	let saving = $state(false);

	async function handleSave() {
		if (!form.validate()) return;
		saving = true;
		try {
			await onsave({
				'app.site_name': form.values.siteName,
				'app.root_url': form.values.rootUrl.replace(/\/+$/, ''),
				'app.logo_url': form.values.logoUrl,
				'app.favicon_url': form.values.faviconUrl,
				'app.from_email': form.values.fromEmail,
				'app.notify_emails': form.values.notifyEmails,
				'app.send_optin_confirmation': form.values.sendOptinConfirmation,
				'app.enable_public_subscription_page': form.values.enablePublicSubPage,
				'app.enable_public_archive': form.values.enablePublicArchive,
				'app.enable_public_archive_rss_content': form.values.enablePublicArchiveRss,
				'app.check_updates': form.values.checkUpdates,
			});
		} finally {
			saving = false;
		}
	}
</script>

<div class="settings-sections">
	<Section title="Site identity">
		<div class="form-fields">
			<FormField label="Site name" error={form.fieldError('siteName')}>
				<Input bind:value={form.values.siteName} onblur={() => form.touch('siteName')} disabled={!canEdit} />
			</FormField>

			<FormField label="Root URL" hint="Public URL of the installation (no trailing slash)." error={form.fieldError('rootUrl')}>
				<Input bind:value={form.values.rootUrl} onblur={() => form.touch('rootUrl')} disabled={!canEdit} placeholder="https://listmonk.yoursite.com" />
			</FormField>

			<div class="form-row">
				<FormField label="Logo URL" hint="Optional. Full URL to logo shown on public pages.">
					<Input bind:value={form.values.logoUrl} disabled={!canEdit} placeholder="https://yoursite.com/logo.png" />
				</FormField>

				<FormField label="Favicon URL" hint="Optional. Full URL to favicon shown on public pages.">
					<Input bind:value={form.values.faviconUrl} disabled={!canEdit} placeholder="https://yoursite.com/favicon.png" />
				</FormField>
			</div>
		</div>
	</Section>

	<Section title="Email defaults">
		<div class="form-fields">
			<FormField label="Default from email" hint="Default from address on outgoing campaign emails. Can be changed per campaign.">
				<Input bind:value={form.values.fromEmail} disabled={!canEdit} placeholder="Listmonk <noreply@yoursite.com>" />
			</FormField>

			<FormField label="Admin notification emails" hint="Receives import updates, campaign completion, failures.">
				<TagInput bind:tags={form.values.notifyEmails} disabled={!canEdit} placeholder="Add email..." />
			</FormField>

			<Switch bind:checked={form.values.sendOptinConfirmation} label="Send opt-in confirmation" hint="Send an opt-in confirmation email when subscribers sign up or are added by an admin." disabled={!canEdit} />
		</div>
	</Section>

	<Section title="Public pages">
		<div class="form-fields">
			<Switch bind:checked={form.values.enablePublicSubPage} label="Enable public subscription page" hint="Show a public page with all public lists for people to subscribe." disabled={!canEdit} />
			<Switch bind:checked={form.values.enablePublicArchive} label="Enable public mailing list archive" hint="Publish campaigns with archiving enabled on the public website." disabled={!canEdit} />
			{#if form.values.enablePublicArchive}
				<Switch bind:checked={form.values.enablePublicArchiveRss} label="Show full content in RSS feed" hint="If disabled, only the title and link elements are shown." disabled={!canEdit} />
			{/if}
		</div>
	</Section>

	<Section title="Updates">
		<Switch bind:checked={form.values.checkUpdates} label="Check for updates" hint="Periodically check for new app releases and notify." disabled={!canEdit} />
	</Section>

	{#if canEdit}
		<div class="tab-actions">
			<Button variant="primary" onclick={handleSave} disabled={saving}>
				{saving ? 'Saving...' : 'Save'}
			</Button>
		</div>
	{/if}
</div>

// apps/admin/src/routes/admin/settings/tabs/GeneralTab.tsx
import { Show, createSignal, untrack } from 'solid-js';
import { Button, FormField, Input, Section, Switch, TagInput } from '~/components';
import type { TabProps } from '../email';

export function GeneralTab(props: TabProps) {
	const [siteName, setSiteName] = createSignal(untrack(() => props.settings['app.site_name'] ?? ''));
	const [rootUrl, setRootUrl] = createSignal(untrack(() => props.settings['app.root_url'] ?? ''));
	const [logoUrl, setLogoUrl] = createSignal(untrack(() => props.settings['app.logo_url'] ?? ''));
	const [faviconUrl, setFaviconUrl] = createSignal(untrack(() => props.settings['app.favicon_url'] ?? ''));
	const [fromEmail, setFromEmail] = createSignal(untrack(() => props.settings['app.from_email'] ?? ''));
	const [notifyEmails, setNotifyEmails] = createSignal(
		untrack(() => props.settings['app.notify_emails'] ?? [])
	);
	const [sendOptinConfirmation, setSendOptinConfirmation] = createSignal(
		untrack(() => props.settings['app.send_optin_confirmation'] ?? false)
	);
	const [enablePublicSubPage, setEnablePublicSubPage] = createSignal(
		untrack(() => props.settings['app.enable_public_subscription_page'] ?? false)
	);
	const [enablePublicArchive, setEnablePublicArchive] = createSignal(
		untrack(() => props.settings['app.enable_public_archive'] ?? false)
	);
	const [enablePublicArchiveRss, setEnablePublicArchiveRss] = createSignal(
		untrack(() => props.settings['app.enable_public_archive_rss_content'] ?? false)
	);
	const [checkUpdates, setCheckUpdates] = createSignal(
		untrack(() => props.settings['app.check_updates'] ?? true)
	);
	const [saving, setSaving] = createSignal(false);

	async function handleSave() {
		setSaving(true);
		try {
			await props.onSave({
				'app.site_name': siteName(),
				'app.root_url': rootUrl().replace(/\/+$/, ''),
				'app.logo_url': logoUrl(),
				'app.favicon_url': faviconUrl(),
				'app.from_email': fromEmail(),
				'app.notify_emails': notifyEmails(),
				'app.send_optin_confirmation': sendOptinConfirmation(),
				'app.enable_public_subscription_page': enablePublicSubPage(),
				'app.enable_public_archive': enablePublicArchive(),
				'app.enable_public_archive_rss_content': enablePublicArchiveRss(),
				'app.check_updates': checkUpdates(),
			});
		} finally {
			setSaving(false);
		}
	}

	return (
		<div class="settings-sections">
			<Section title="Site identity">
				<div class="form-fields">
					<FormField label="Site name">
						<Input value={siteName()} onInput={(e) => setSiteName(e.currentTarget.value)} disabled={!props.canEdit} />
					</FormField>
					<FormField label="Root URL" hint="Public URL of the installation (no trailing slash).">
						<Input type="url" value={rootUrl()} onInput={(e) => setRootUrl(e.currentTarget.value)} disabled={!props.canEdit} placeholder="https://listmonk.yoursite.com" />
					</FormField>
					<div class="form-row">
						<FormField label="Logo URL" hint="Optional. Full URL to logo shown on public pages.">
							<Input value={logoUrl()} onInput={(e) => setLogoUrl(e.currentTarget.value)} disabled={!props.canEdit} placeholder="https://yoursite.com/logo.png" />
						</FormField>
						<FormField label="Favicon URL" hint="Optional. Full URL to favicon shown on public pages.">
							<Input value={faviconUrl()} onInput={(e) => setFaviconUrl(e.currentTarget.value)} disabled={!props.canEdit} placeholder="https://yoursite.com/favicon.png" />
						</FormField>
					</div>
				</div>
			</Section>

			<Section title="Email defaults">
				<div class="form-fields">
					<FormField label="Default from email" hint="Default from address on outgoing campaign emails. Can be changed per campaign.">
						<Input value={fromEmail()} onInput={(e) => setFromEmail(e.currentTarget.value)} disabled={!props.canEdit} placeholder="Listmonk <noreply@yoursite.com>" />
					</FormField>
					<FormField label="Admin notification emails" hint="Receives import updates, campaign completion, and failures.">
						<TagInput
							tags={notifyEmails()}
							onChange={setNotifyEmails}
							validate={(v) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)}
							placeholder="admin@example.com"
							disabled={!props.canEdit}
						/>
					</FormField>
					<Switch
						label="Send opt-in confirmation"
						hint="Send an opt-in confirmation email when subscribers sign up or are added by an admin."
						checked={sendOptinConfirmation()}
						onChange={setSendOptinConfirmation}
						disabled={!props.canEdit}
					/>
				</div>
			</Section>

			<Section title="Public pages">
				<div class="form-fields">
					<Switch
						label="Enable public subscription page"
						hint="Show a public page with all public lists for people to subscribe."
						checked={enablePublicSubPage()}
						onChange={setEnablePublicSubPage}
						disabled={!props.canEdit}
					/>
					<Switch
						label="Enable public mailing list archive"
						hint="Publish campaigns with archiving enabled on the public website."
						checked={enablePublicArchive()}
						onChange={setEnablePublicArchive}
						disabled={!props.canEdit}
					/>
					<Show when={enablePublicArchive()}>
						<Switch
							label="Show full content in RSS feed"
							hint="If disabled, only the title and link elements are shown."
							checked={enablePublicArchiveRss()}
							onChange={setEnablePublicArchiveRss}
							disabled={!props.canEdit}
						/>
					</Show>
				</div>
			</Section>

			<Section title="Updates">
				<div class="form-fields">
					<Switch
						label="Check for updates"
						hint="Periodically check for new app releases and notify."
						checked={checkUpdates()}
						onChange={setCheckUpdates}
						disabled={!props.canEdit}
					/>
				</div>
			</Section>

			<Show when={props.canEdit}>
				<div class="tab-actions">
					<Button onClick={handleSave} disabled={saving()}>{saving() ? 'Saving…' : 'Save'}</Button>
				</div>
			</Show>
		</div>
	);
}
