// src/routes/admin/emails/campaigns/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { Spinner } from '$lib/components/admin';
	import { getCampaign } from '../../campaigns.remote';
	import CampaignEditor from '../CampaignEditor.svelte';

	let id = $derived(Number($page.params.id));
	let campaignQuery = $derived(getCampaign(id));
	let _prev: typeof campaignQuery.current;
	let campaign = $derived.by(() => {
		const val = campaignQuery.current;
		if (val !== undefined) _prev = val;
		return val ?? _prev;
	});
</script>

{#if !campaign && campaignQuery.loading}
	<Spinner size={48} centered />
{:else if campaign}
	<CampaignEditor mode="edit" {campaign} />
{/if}

// apps/admin/src/routes/(app)/emails/campaigns/[id].tsx
import { createAsync, useParams, type RouteDefinition } from '@solidjs/router';
import { Show } from 'solid-js';
import { Spinner } from '~/components';
import { getCampaign } from '../campaigns.server';
import { CampaignEditor } from './CampaignEditor';
import './CampaignEditor.css';

export const route: RouteDefinition = {
	preload: ({ params }) => {
		void getCampaign(Number(params['id']));
	},
};

export default function CampaignDetailPage() {
	const params = useParams();
	const campaign = createAsync(() => getCampaign(Number(params['id'])));

	return (
		<Show when={campaign()} fallback={<Spinner centered />}>
			{(c) => <CampaignEditor mode="edit" campaign={c()} />}
		</Show>
	);
}
