// apps/admin/src/routes/(app)/settings/email.tsx
import { createAsync, revalidate, type RouteDefinition } from '@solidjs/router';
import { Show, createMemo, createSignal } from 'solid-js';
import { toast } from 'solid-sonner';
import { Card, PageHeader, Tabs, TabContent } from '~/components';
import { getSession } from '~/routes/session';
import { can } from '~/lib/can';
import { toastError } from '~/lib/utils';
import { getEmailSettings, updateEmailSettings } from '../settings.server';
import type { ListmonkSettings } from '~/server/listmonk';
import { GeneralTab } from './tabs/GeneralTab';
import { SmtpTab } from './tabs/SmtpTab';
import { PerformanceTab } from './tabs/PerformanceTab';
import { BounceTab } from './tabs/BounceTab';
import { PrivacyTab } from './tabs/PrivacyTab';
import './email.css';

export const route: RouteDefinition = {
	preload: () => { void getEmailSettings(); },
};

// Shared prop type for all tab components
export type TabProps = {
	settings: ListmonkSettings;
	canEdit: boolean;
	onSave: (p: Partial<ListmonkSettings>) => Promise<void>;
};

export default function EmailSettingsPage() {
	const session = createAsync(() => getSession());
	const settings = createAsync(() => getEmailSettings());
	const canEdit = createMemo(() => can(session(), 'settings', 'edit'));
	const [activeTab, setActiveTab] = createSignal('general');

	async function save(partial: Partial<ListmonkSettings>) {
		try {
			await updateEmailSettings(partial);
			toast.success('Settings saved.');
			await revalidate('getEmailSettings');
		} catch (err) {
			toastError(err, 'Failed to save settings.');
		}
	}

	return (
		<>
			<PageHeader title="Email Settings" />

			<Show when={settings()} keyed>
				{(s) => (
					<Card>
						<Tabs
							value={activeTab()}
							onChange={setActiveTab}
							tabs={[
								{ value: 'general', label: 'General' },
								{ value: 'smtp', label: 'SMTP' },
								{ value: 'performance', label: 'Performance' },
								{ value: 'bounce', label: 'Bounces' },
								{ value: 'privacy', label: 'Privacy' },
							]}
						>
							<TabContent value="general">
								<GeneralTab settings={s} canEdit={canEdit()} onSave={save} />
							</TabContent>
							<TabContent value="smtp">
								<SmtpTab settings={s} canEdit={canEdit()} onSave={save} />
							</TabContent>
							<TabContent value="performance">
								<PerformanceTab settings={s} canEdit={canEdit()} onSave={save} />
							</TabContent>
							<TabContent value="bounce">
								<BounceTab settings={s} canEdit={canEdit()} onSave={save} />
							</TabContent>
							<TabContent value="privacy">
								<PrivacyTab settings={s} canEdit={canEdit()} onSave={save} />
							</TabContent>
						</Tabs>
					</Card>
				)}
			</Show>
		</>
	);
}

// src/routes/admin/settings/email/+page.svelte
<script lang="ts">
	import { Breadcrumb, Card, Tabs, TabContent } from '$lib/components/admin';
	import { toast } from 'svelte-sonner';
	import { toastError } from '$lib/utils/toast-error';
	import { getEmailSettings, updateEmailSettings } from '../../settings.remote';
	import { getSession } from '../../session.remote';
	import { can } from '../../can';

	import GeneralTab from './components/GeneralTab.svelte';
	import SmtpTab from './components/SmtpTab.svelte';
	import PerformanceTab from './components/PerformanceTab.svelte';
	import BounceTab from './components/BounceTab.svelte';
	import PrivacyTab from './components/PrivacyTab.svelte';

	let [session, settings] = $derived(await Promise.all([getSession(), getEmailSettings()]));
	let canEdit = $derived(can(session, 'settings', 'edit'));

	let activeTab = $state('general');

	async function handleSave(partial: Record<string, unknown>) {
		try {
			// Listmonk requires the full settings object on PUT — merge changes into current state
			await updateEmailSettings({ ...settings, ...partial });
			toast.success('Settings saved.');
			getEmailSettings().refresh();
		} catch (err) {
			toastError(err, 'Failed to save settings.');
		}
	}
</script>

<Breadcrumb items={[{ label: 'Settings' }, { label: 'Email' }]} />

<h1>Email Settings</h1>

{#if settings}
{#key settings}
	<Card>
		<Tabs bind:value={activeTab} tabs={[
			{ value: 'general', label: 'General' },
			{ value: 'smtp', label: 'SMTP' },
			{ value: 'performance', label: 'Performance' },
			{ value: 'bounce', label: 'Bounces' },
			{ value: 'privacy', label: 'Privacy' },
		]}>
			<TabContent value="general">
				<GeneralTab {settings} {canEdit} onsave={handleSave} />
			</TabContent>
			<TabContent value="smtp">
				<SmtpTab {settings} {canEdit} onsave={handleSave} />
			</TabContent>
			<TabContent value="performance">
				<PerformanceTab {settings} {canEdit} onsave={handleSave} />
			</TabContent>
			<TabContent value="bounce">
				<BounceTab {settings} {canEdit} onsave={handleSave} />
			</TabContent>
			<TabContent value="privacy">
				<PrivacyTab {settings} {canEdit} onsave={handleSave} />
			</TabContent>
		</Tabs>
	</Card>
{/key}
{/if}
