// src/lib/components/admin/Spinner.svelte
<script lang="ts">
  let {
    size = 24,
    centered = false,
  }: {
    size?: number;
    centered?: boolean;
  } = $props();
</script>

{#if centered}
  <div class="spinner-container">
    <svg
      class="spinner"
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      role="status"
      aria-label="Loading"
    >
      <circle class="track" cx="12" cy="12" r="10" stroke-width="3" />
      <path class="arc" d="M12 2a10 10 0 0 1 10 10" stroke-width="3" stroke-linecap="round" />
    </svg>
  </div>
{:else}
  <svg
    class="spinner"
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    role="status"
    aria-label="Loading"
  >
    <circle class="track" cx="12" cy="12" r="10" stroke-width="3" />
    <path class="arc" d="M12 2a10 10 0 0 1 10 10" stroke-width="3" stroke-linecap="round" />
  </svg>
{/if}

<style>
  .spinner-container {
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 4rem 0;
  }

  .spinner {
    display: block;
    animation: spin 0.8s linear infinite;
  }

  .track {
    stroke: var(--color-border);
    opacity: 0.3;
  }

  .arc {
    stroke: var(--brand-orange);
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }
</style>

// apps/admin/src/components/admin/Spinner.tsx
import type { Component } from "solid-js";
import { Show } from "solid-js";
import "./Spinner.css";

type SpinnerProps = {
  size?: number;
  centered?: boolean;
};

const SpinnerSvg: Component<{ size: number }> = (props) => (
  <svg
    class="spinner"
    width={props.size}
    height={props.size}
    viewBox="0 0 24 24"
    fill="none"
    role="status"
    aria-label="Loading"
  >
    <circle class="spinner-track" cx="12" cy="12" r="10" stroke-width="3" />
    <path class="spinner-arc" d="M12 2a10 10 0 0 1 10 10" stroke-width="3" stroke-linecap="round" />
  </svg>
);

export const Spinner: Component<SpinnerProps> = (props) => {
  return (
    <Show
      when={props.centered}
      fallback={<SpinnerSvg size={props.size ?? 24} />}
    >
      <div class="spinner-container">
        <SpinnerSvg size={props.size ?? 24} />
      </div>
    </Show>
  );
};
