// src/lib/components/admin/StatCard.svelte
<script lang="ts">
	let {
		value,
		label,
		accent,
	}: {
		value: string | number;
		label: string;
		accent?: string;
	} = $props();
</script>

<div class="stat-card" style:border-top-color={accent}>
	<span class="stat-value">{value}</span>
	<span class="stat-label">{label}</span>
</div>

<style>
	.stat-card {
		background: var(--color-surface);
		border-radius: var(--radius-lg);
		padding: 1.25rem;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
		box-shadow: var(--shadow-sm);
		border-top: 3px solid transparent;
	}

	.stat-value {
		font-size: 1.75rem;
		font-weight: 700;
		color: var(--color-foreground);
	}

	.stat-label {
		font-size: 0.85rem;
		color: var(--color-muted);
	}
</style>

// apps/admin/src/components/admin/StatCard.tsx
import type { Component } from "solid-js";
import "./StatCard.css";

type StatCardProps = {
  value: string | number;
  label: string;
  accent?: string;
};

export const StatCard: Component<StatCardProps> = (props) => {
  return (
    <div
      class="stat-card"
      style={props.accent ? { "border-top-color": props.accent } : undefined}
    >
      <span class="stat-value">{props.value}</span>
      <span class="stat-label">{props.label}</span>
    </div>
  );
};
