// src/lib/components/admin/QRCode.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Switch } from "$lib/components/admin";
  import { getLogoDataUrl } from "./logo-path";

  let {
    url,
    title = "qr-code",
  }: {
    url: string;
    title?: string;
  } = $props();

  const presets = [
    { name: "Brown", fg: "#361d12", bg: "#fff7ef" },
    { name: "Orange", fg: "#ff6f00", bg: "#ffffff" },
    { name: "Magenta", fg: "#8f005a", bg: "#ffffff" },
    { name: "Inverted", fg: "#fff7ef", bg: "#361d12" },
  ];

  const dotStyles = [
    { name: "Rounded", value: "rounded" },
    { name: "Dots", value: "dots" },
    { name: "Square", value: "square" },
    { name: "Classy", value: "classy" },
    { name: "Classy Rounded", value: "classy-rounded" },
    { name: "Extra Rounded", value: "extra-rounded" },
  ] as const;

  const cornerStyles = [
    { name: "Extra Rounded", value: "extra-rounded" },
    { name: "Square", value: "square" },
    { name: "Dot", value: "dot" },
    { name: "Rounded", value: "rounded" },
    { name: "Classy", value: "classy" },
    { name: "Classy Rounded", value: "classy-rounded" },
  ] as const;

  let selectedPreset = $state(0);
  let selectedDotStyle = $state(0);
  let selectedCornerStyle = $state(0);
  let showLogo = $state(false);
  let qrContainer: HTMLDivElement;
  type QRCodeStylingInstance = {
    append: (el: HTMLElement) => void;
    download: (opts: { name: string; extension: string }) => void;
    getRawData: (ext: string) => Promise<Blob>;
  };

  let QRCodeStyling: any;
  let qr: QRCodeStylingInstance;

  onMount(async () => {
    const mod = await import("qr-code-styling");
    QRCodeStyling = mod.default;
    renderQR();
  });

  function renderQR() {
    if (!QRCodeStyling || !qrContainer) return;

    const preset = presets[selectedPreset];
    const dotType = dotStyles[selectedDotStyle].value;
    const cornerType = cornerStyles[selectedCornerStyle].value;
    const opts: any = {
      width: 1000,
      height: 1000,
      data: url,
      margin: 8,
      dotsOptions: {
        color: preset.fg,
        type: dotType,
      },
      cornersSquareOptions: {
        type: cornerType,
        color: preset.fg,
      },
      cornersDotOptions: {
        type: cornerType === "extra-rounded" ? "dot" : cornerType,
        color: preset.fg,
      },
      backgroundOptions: {
        color: preset.bg,
      },
      qrOptions: {
        errorCorrectionLevel: "H",
      },
    };

    if (showLogo) {
      opts.image = getLogoDataUrl(preset.fg);
      opts.imageOptions = {
        crossOrigin: "anonymous",
        margin: 4,
        imageSize: 0.35,
      };
    }

    qrContainer.innerHTML = "";
    qr = new QRCodeStyling(opts);
    qr.append(qrContainer);
  }

  $effect(() => {
    selectedPreset;
    selectedDotStyle;
    selectedCornerStyle;
    showLogo;
    url;
    renderQR();
  });

  function downloadSVG() {
    qr?.download({ name: `qr-${title}`, extension: "svg" });
  }

  function downloadPNG() {
    qr?.download({ name: `qr-${title}`, extension: "png" });
  }
</script>

<div class="qr-wrapper">
  <div class="qr-image" bind:this={qrContainer}></div>
  <div class="qr-controls">
    <div class="qr-downloads">
      <button class="dl-btn" onclick={downloadSVG}>SVG</button>
      <button class="dl-btn" onclick={downloadPNG}>PNG</button>
    </div>
    <div class="qr-presets">
      {#each presets as preset, i}
        <button
          class="preset-btn"
          class:preset-active={selectedPreset === i}
          onclick={() => (selectedPreset = i)}
          aria-label={preset.name}
          title={preset.name}
        >
          <span
            class="preset-swatch"
            style:background={preset.fg}
            style:border-color={preset.fg === "#ffffff" ? "#d1d5db" : preset.fg}
          ></span>
        </button>
      {/each}
    </div>
    <div class="qr-picker">
      <span class="picker-label">Dots</span>
      <select
        class="picker-select"
        value={selectedDotStyle}
        onchange={(e) =>
          (selectedDotStyle = Number(
            (e.target as HTMLSelectElement).value,
          ))}
      >
        {#each dotStyles as style, i}
          <option value={i}>{style.name}</option>
        {/each}
      </select>
    </div>
    <div class="qr-picker">
      <span class="picker-label">Corners</span>
      <select
        class="picker-select"
        value={selectedCornerStyle}
        onchange={(e) =>
          (selectedCornerStyle = Number(
            (e.target as HTMLSelectElement).value,
          ))}
      >
        {#each cornerStyles as style, i}
          <option value={i}>{style.name}</option>
        {/each}
      </select>
    </div>
    <Switch label="Logo" bind:checked={showLogo} />
  </div>
</div>

<style>
  .qr-wrapper {
    display: flex;
    align-items: center;
    gap: 1rem;
    flex: 1;
  }

  .qr-image {
    flex: 1;
    min-width: 0;
  }

  .qr-image :global(canvas),
  .qr-image :global(svg) {
    display: block;
    width: 100%;
    height: auto;
    border-radius: var(--radius-md);
  }

  .qr-controls {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
    flex-shrink: 0;
  }

  .qr-downloads {
    display: flex;
    gap: 0.35rem;
  }

  .dl-btn {
    padding: 0.3rem 0.75rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    background: var(--color-surface);
    color: var(--color-muted);
    font-size: 0.8rem;
    font-weight: 500;
    cursor: pointer;
    transition:
      background 0.15s,
      color 0.15s;
  }

  .dl-btn:hover {
    background: var(--color-hover);
    color: var(--color-foreground);
  }

  .qr-presets {
    display: flex;
    gap: 0.35rem;
  }

  .preset-btn {
    padding: 3px;
    border: 2px solid transparent;
    border-radius: 50%;
    background: none;
    cursor: pointer;
    transition: border-color 0.15s;
  }

  .preset-active {
    border-color: var(--color-primary);
  }

  .preset-swatch {
    display: block;
    width: 20px;
    height: 20px;
    border-radius: 50%;
    border: 1px solid;
  }

  .qr-picker {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .picker-label {
    font-size: 0.7rem;
    text-transform: uppercase;
    letter-spacing: 0.03em;
    color: var(--color-muted);
  }

  .picker-select {
    padding: 0.3rem 0.5rem;
    border: 1px solid var(--color-border);
    border-radius: var(--radius-sm);
    background: var(--color-surface);
    color: var(--color-foreground);
    font-size: 0.8rem;
    cursor: pointer;
    transition: border-color 0.15s;
  }

  .picker-select:hover {
    border-color: var(--color-primary);
  }

  .picker-select:focus {
    outline: none;
    border-color: var(--color-primary);
  }
</style>

// apps/admin-v2/src/ui/qr-code.tsx
import QRCodeStyling from 'qr-code-styling';
import { For, Show, createEffect, createMemo, createSignal, onSettled, untrack } from 'solid-js';
import { logoDataUrl } from './logo-data-url';
import './qr-code.css';

const colorPresets = [
	{ name: 'Brown', foreground: '#361d12', background: '#ffffff' },
	{ name: 'Orange', foreground: '#ff6f00', background: '#ffffff' },
	{ name: 'Magenta', foreground: '#8f005a', background: '#ffffff' },
	{ name: 'Inverted', foreground: '#fff7ef', background: '#262637' },
] as const;

const dotStyles = [
	{ name: 'Rounded', value: 'rounded' },
	{ name: 'Dots', value: 'dots' },
	{ name: 'Square', value: 'square' },
	{ name: 'Classy', value: 'classy' },
	{ name: 'Classy Rounded', value: 'classy-rounded' },
	{ name: 'Extra Rounded', value: 'extra-rounded' },
] as const;

const cornerStyles = [
	{ name: 'Extra Rounded', value: 'extra-rounded' },
	{ name: 'Square', value: 'square' },
	{ name: 'Dot', value: 'dot' },
	{ name: 'Rounded', value: 'rounded' },
	{ name: 'Classy', value: 'classy' },
	{ name: 'Classy Rounded', value: 'classy-rounded' },
] as const;

export type QrCodeProps = {
	color?: string;
	label: string;
	title?: string;
	url: string;
};

function downloadName(title: string | undefined): string {
	const safeTitle = title?.trim().replace(/[^a-zA-Z0-9._-]+/g, '-') || 'qr-code';
	return `qr-${safeTitle}`;
}

export function QrCode(props: QrCodeProps) {
	let container: HTMLDivElement | undefined;
	let instance: QRCodeStyling | undefined;
	const [ready, setReady] = createSignal(false);
	const [error, setError] = createSignal<string>();
	const [selectedPreset, setSelectedPreset] = createSignal(0);
	const [selectedDotStyle, setSelectedDotStyle] = createSignal(0);
	const [selectedCornerStyle, setSelectedCornerStyle] = createSignal(0);
	const [showLogo, setShowLogo] = createSignal(false);
	const selectedForeground = createMemo(() =>
		selectedPreset() === 0 && props.color ? props.color : colorPresets[selectedPreset()]!.foreground,
	);
	const selectedBackground = createMemo(() => colorPresets[selectedPreset()]!.background);

	function reportFailure(cause: unknown, message = 'QR preview could not be generated.'): void {
		console.error('[QrCode] Failed to render QR code', cause);
		setReady(false);
		setError(message);
	}

	onSettled(() => {
		setError(undefined);
		const initial = untrack(() => ({
			background: selectedBackground(),
			corner: cornerStyles[selectedCornerStyle()]!.value,
			dot: dotStyles[selectedDotStyle()]!.value,
			foreground: selectedForeground(),
			logo: showLogo(),
			url: props.url,
		}));
		try {
			if (!container) return;
			instance = new QRCodeStyling({
				type: 'svg',
				width: 1000,
				height: 1000,
				margin: 8,
				data: initial.url,
				image: initial.logo ? logoDataUrl(initial.foreground) : undefined,
				imageOptions: { crossOrigin: 'anonymous', hideBackgroundDots: true, imageSize: 0.35, margin: 4 },
				dotsOptions: { color: initial.foreground, type: initial.dot },
				cornersSquareOptions: { color: initial.foreground, type: initial.corner },
				cornersDotOptions: { color: initial.foreground, type: initial.corner === 'extra-rounded' ? 'dot' : initial.corner },
				backgroundOptions: { color: initial.background },
				qrOptions: { errorCorrectionLevel: 'H' },
			});
			container.replaceChildren();
			instance.append(container);
			if (initial.url.trim()) setReady(true);
			else setError('Enter a QR destination.');
		} catch (cause) {
			reportFailure(cause);
		}

		return () => {
			setReady(false);
			instance = undefined;
			container?.replaceChildren();
		};
	});

	createEffect(
		() => ({
			background: selectedBackground(),
			corner: cornerStyles[selectedCornerStyle()]!.value,
			dot: dotStyles[selectedDotStyle()]!.value,
			foreground: selectedForeground(),
			logo: showLogo(),
			url: props.url,
		}),
		(state) => {
			if (!instance) return;
			if (!state.url.trim()) {
				setReady(false);
				setError('Enter a QR destination.');
				return;
			}

			try {
				instance.update({
					data: state.url,
					image: state.logo ? logoDataUrl(state.foreground) : undefined,
					dotsOptions: { color: state.foreground, type: state.dot },
					cornersSquareOptions: { color: state.foreground, type: state.corner },
					cornersDotOptions: { color: state.foreground, type: state.corner === 'extra-rounded' ? 'dot' : state.corner },
					backgroundOptions: { color: state.background },
				});
				setError(undefined);
				setReady(true);
			} catch (cause) {
				reportFailure(cause);
			}
		},
	);

	async function download(extension: 'svg' | 'png'): Promise<void> {
		if (!instance || !ready()) return;
		try {
			await instance.download({ name: downloadName(props.title), extension });
		} catch (cause) {
			reportFailure(cause, 'QR code could not be downloaded.');
		}
	}

	return (
		<div class="qr-code-widget">
			<div
				ref={(element) => {
					container = element;
				}}
				class="qr-code"
				role={error() ? undefined : 'img'}
				aria-label={error() ? undefined : props.label}
				aria-busy={!error() && !ready() ? 'true' : undefined}
				hidden={!!error()}
			/>
			<Show when={error()}>
				{(message) => <p class="qr-code-error" role="alert">{message()}</p>}
			</Show>
			<div class="qr-code-controls" role="group" aria-label="QR code appearance">
				<div class="qr-code-downloads">
					<button type="button" onClick={() => void download('svg')} disabled={!ready()}>Download SVG</button>
					<button type="button" onClick={() => void download('png')} disabled={!ready()}>Download PNG</button>
				</div>
				<div class="qr-code-presets" role="group" aria-label="Color preset">
					<For each={colorPresets}>
						{(preset, index) => (
							<button
								type="button"
								class={['qr-code-preset', { 'qr-code-preset--active': selectedPreset() === index() }]}
								onClick={() => setSelectedPreset(index())}
								aria-label={preset.name}
								aria-pressed={selectedPreset() === index() ? 'true' : 'false'}
							>
								<span style={{ background: index() === 0 && props.color ? props.color : preset.foreground }} />
							</button>
						)}
					</For>
				</div>
				<label>
					<span>Dots</span>
					<select value={selectedDotStyle()} onChange={(event) => setSelectedDotStyle(Number(event.currentTarget.value))}>
						<For each={dotStyles}>{(style, index) => <option value={index()}>{style.name}</option>}</For>
					</select>
				</label>
				<label>
					<span>Corners</span>
					<select value={selectedCornerStyle()} onChange={(event) => setSelectedCornerStyle(Number(event.currentTarget.value))}>
						<For each={cornerStyles}>{(style, index) => <option value={index()}>{style.name}</option>}</For>
					</select>
				</label>
				<label class="qr-code-logo-option">
					<input type="checkbox" checked={showLogo()} onInput={(event) => setShowLogo(event.currentTarget.checked)} />
					Include logo
				</label>
			</div>
		</div>
	);
}
