// src/lib/components/admin/RichTextEditor.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Popover } from 'bits-ui';
	import Button from './Button.svelte';
	import Input from './Input.svelte';

	let {
		value = '',
		onchange,
	}: {
		value?: string;
		onchange?: (html: string) => void;
	} = $props();

	let editorRef: HTMLDivElement;
	let isBold = $state(false);
	let isItalic = $state(false);
	let isUnderline = $state(false);
	let isStrikethrough = $state(false);
	let blockType = $state('paragraph');
	let linkActive = $state(false);
	let ready = $state(false);
	let linkPopoverOpen = $state(false);
	let linkUrl = $state('');
	let linkInputEl = $state<HTMLInputElement | null>(null);

	// Hold references populated in onMount
	let editorInstance: any;
	let FORMAT_TEXT: any;
	let INSERT_UL: any;
	let INSERT_OL: any;
	let TOGGLE_LINK: any;
	let lex: any;
	let rt: any;
	let html: any;
	let sel: any;
	let lnk: any;

	onMount(async () => {
		lex = await import('lexical');
		rt = await import('@lexical/rich-text');
		html = await import('@lexical/html');
		const list = await import('@lexical/list');
		lnk = await import('@lexical/link');
		sel = await import('@lexical/selection');

		FORMAT_TEXT = lex.FORMAT_TEXT_COMMAND;
		INSERT_UL = list.INSERT_UNORDERED_LIST_COMMAND;
		INSERT_OL = list.INSERT_ORDERED_LIST_COMMAND;
		TOGGLE_LINK = lnk.TOGGLE_LINK_COMMAND;

		editorInstance = lex.createEditor({
			namespace: 'RichTextEditor',
			nodes: [rt.HeadingNode, rt.QuoteNode, list.ListNode, list.ListItemNode, lnk.LinkNode, lnk.AutoLinkNode],
			onError: (error: Error) => console.error('[RichTextEditor]', error),
			theme: {
				text: {
					bold: 'rte-bold',
					italic: 'rte-italic',
					underline: 'rte-underline',
					strikethrough: 'rte-strikethrough',
					code: 'rte-code',
				},
				heading: { h1: 'rte-h1', h2: 'rte-h2', h3: 'rte-h3' },
				list: { ul: 'rte-ul', ol: 'rte-ol', listitem: 'rte-li' },
				quote: 'rte-blockquote',
				link: 'rte-link',
			},
		});

		editorInstance.setRootElement(editorRef);
		rt.registerRichText(editorInstance);
		list.registerList(editorInstance);

		if (value) {
			editorInstance.update(() => {
				const parser = new DOMParser();
				const dom = parser.parseFromString(value, 'text/html');
				const nodes = html.$generateNodesFromDOM(editorInstance, dom);
				const root = lex.$getRoot();
				root.clear();
				root.append(...nodes);
			});
		}

		editorInstance.registerUpdateListener(({ editorState }: any) => {
			editorState.read(() => {
				const selection = lex.$getSelection();
				if (lex.$isRangeSelection(selection)) {
					isBold = selection.hasFormat('bold');
					isItalic = selection.hasFormat('italic');
					isUnderline = selection.hasFormat('underline');
					isStrikethrough = selection.hasFormat('strikethrough');

					const anchorNode = selection.anchor.getNode();
					const element = anchorNode.getKey() === 'root'
						? anchorNode
						: anchorNode.getTopLevelElementOrThrow();

					if (rt.$isHeadingNode(element)) {
						blockType = element.getTag();
					} else if (element.getType() === 'quote') {
						blockType = 'quote';
					} else {
						blockType = element.getType();
					}

					const parent = anchorNode.getParent();
					linkActive = lnk.$isLinkNode(parent) || lnk.$isLinkNode(anchorNode);
				}
			});

			editorState.read(() => {
				const h = html.$generateHtmlFromNodes(editorInstance);
				onchange?.(h);
			});
		});

		ready = true;
	});

	function formatText(format: 'bold' | 'italic' | 'underline' | 'strikethrough') {
		editorInstance.dispatchCommand(FORMAT_TEXT, format);
	}

	function formatHeading(tag: 'h1' | 'h2' | 'h3') {
		editorInstance.update(() => {
			const selection = lex.$getSelection();
			if (lex.$isRangeSelection(selection)) {
				if (blockType === tag) {
					sel.$setBlocksType(selection, () => lex.$createParagraphNode());
				} else {
					sel.$setBlocksType(selection, () => rt.$createHeadingNode(tag));
				}
			}
		});
	}

	function formatQuote() {
		editorInstance.update(() => {
			const selection = lex.$getSelection();
			if (lex.$isRangeSelection(selection)) {
				if (blockType === 'quote') {
					sel.$setBlocksType(selection, () => lex.$createParagraphNode());
				} else {
					sel.$setBlocksType(selection, () => rt.$createQuoteNode());
				}
			}
		});
	}

	function insertList(type: 'bullet' | 'number') {
		if (type === 'bullet') {
			editorInstance.dispatchCommand(INSERT_UL, undefined);
		} else {
			editorInstance.dispatchCommand(INSERT_OL, undefined);
		}
	}

	function toggleLink() {
		if (linkActive) {
			editorInstance.dispatchCommand(TOGGLE_LINK, null);
		} else {
			linkUrl = '';
			linkPopoverOpen = true;
			// Focus the input after it renders
			requestAnimationFrame(() => linkInputEl?.focus());
		}
	}

	function applyLink() {
		const url = linkUrl.trim();
		if (url) {
			editorInstance.dispatchCommand(TOGGLE_LINK, url);
		}
		linkPopoverOpen = false;
		editorRef?.focus();
	}

	function handleLinkKeydown(e: KeyboardEvent) {
		if (e.key === 'Enter') {
			e.preventDefault();
			applyLink();
		} else if (e.key === 'Escape') {
			linkPopoverOpen = false;
			editorRef?.focus();
		}
	}
</script>

<div class="rte-container">
	<div class="rte-toolbar" class:disabled={!ready}>
		<div class="rte-toolbar-group">
			<button type="button" class="rte-btn" class:active={isBold} onclick={() => formatText('bold')} title="Bold" disabled={!ready}>
				<strong>B</strong>
			</button>
			<button type="button" class="rte-btn" class:active={isItalic} onclick={() => formatText('italic')} title="Italic" disabled={!ready}>
				<em>I</em>
			</button>
			<button type="button" class="rte-btn" class:active={isUnderline} onclick={() => formatText('underline')} title="Underline" disabled={!ready}>
				<u>U</u>
			</button>
			<button type="button" class="rte-btn" class:active={isStrikethrough} onclick={() => formatText('strikethrough')} title="Strikethrough" disabled={!ready}>
				<s>S</s>
			</button>
		</div>

		<div class="rte-toolbar-divider"></div>

		<div class="rte-toolbar-group">
			<button type="button" class="rte-btn" class:active={blockType === 'h1'} onclick={() => formatHeading('h1')} title="Heading 1" disabled={!ready}>H1</button>
			<button type="button" class="rte-btn" class:active={blockType === 'h2'} onclick={() => formatHeading('h2')} title="Heading 2" disabled={!ready}>H2</button>
			<button type="button" class="rte-btn" class:active={blockType === 'h3'} onclick={() => formatHeading('h3')} title="Heading 3" disabled={!ready}>H3</button>
		</div>

		<div class="rte-toolbar-divider"></div>

		<div class="rte-toolbar-group">
			<button type="button" class="rte-btn" onclick={() => insertList('bullet')} title="Bullet List" disabled={!ready}>&bull;</button>
			<button type="button" class="rte-btn" onclick={() => insertList('number')} title="Numbered List" disabled={!ready}>1.</button>
			<button type="button" class="rte-btn" class:active={blockType === 'quote'} onclick={() => formatQuote()} title="Blockquote" disabled={!ready}>&ldquo;</button>
		</div>

		<div class="rte-toolbar-divider"></div>

		<div class="rte-toolbar-group">
			<Popover.Root bind:open={linkPopoverOpen}>
				<Popover.Trigger>
					{#snippet child({ props })}
						<button {...props} type="button" class="rte-btn" class:active={linkActive} onclick={() => toggleLink()} title="Link" disabled={!ready}>&#128279;</button>
					{/snippet}
				</Popover.Trigger>
				<Popover.Content class="rte-link-popover" sideOffset={6} onOpenAutoFocus={(e) => { e.preventDefault(); requestAnimationFrame(() => linkInputEl?.focus()); }}>
					<form class="rte-link-form" onsubmit={(e: SubmitEvent) => { e.preventDefault(); applyLink(); }}>
						<Input bind:ref={linkInputEl} type="url" bind:value={linkUrl} placeholder="https://..." onkeydown={handleLinkKeydown} class="rte-link-input" />
						<Button variant="primary" type="submit">Apply</Button>
					</form>
				</Popover.Content>
			</Popover.Root>
		</div>
	</div>

	<div class="rte-editor" contenteditable="true" bind:this={editorRef}></div>
</div>

<style>
	.rte-container {
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		overflow: hidden;
		background: var(--color-surface);
	}

	.rte-toolbar {
		display: flex;
		align-items: center;
		gap: 0.25rem;
		padding: 0.375rem 0.5rem;
		border-bottom: 1px solid var(--color-border);
		background: var(--color-page-bg);
		flex-wrap: wrap;
	}

	.rte-toolbar.disabled {
		opacity: 0.5;
		pointer-events: none;
	}

	.rte-toolbar-group {
		display: flex;
		gap: 0.125rem;
	}

	.rte-toolbar-divider {
		width: 1px;
		height: 1.25rem;
		background: var(--color-border);
		margin: 0 0.25rem;
	}

	.rte-btn {
		background: none;
		border: 1px solid transparent;
		border-radius: var(--radius-sm);
		cursor: pointer;
		color: var(--color-muted);
		font-size: 0.8rem;
		padding: 0.25rem 0.5rem;
		min-width: 1.75rem;
		text-align: center;
		line-height: 1;
		transition: all 0.1s ease;
	}

	.rte-btn:hover:not(:disabled) {
		color: var(--color-foreground);
		background: var(--color-hover);
	}

	.rte-btn.active {
		color: var(--color-primary);
		background: color-mix(in srgb, var(--color-primary) 10%, transparent);
		border-color: color-mix(in srgb, var(--color-primary) 25%, transparent);
	}

	/* ─── Link popover ────────────────────────────────────────── */

	:global(.rte-link-popover) {
		background: var(--color-surface);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-md);
		box-shadow: var(--shadow-lg);
		padding: 0.5rem;
		z-index: var(--z-dropdown);
	}

	:global(.rte-link-form) {
		display: flex;
		align-items: center;
		gap: 0.375rem;
	}

	:global(.rte-link-input) {
		width: 220px;
	}

	.rte-editor {
		min-height: 200px;
		padding: 0.75rem 1rem;
		outline: none;
		font-size: 0.9rem;
		line-height: 1.6;
		color: var(--color-foreground);
	}

	.rte-editor:focus {
		box-shadow: inset 0 0 0 2px color-mix(in srgb, var(--color-primary) 15%, transparent);
	}

	:global(.rte-bold) { font-weight: 700; }
	:global(.rte-italic) { font-style: italic; }
	:global(.rte-underline) { text-decoration: underline; }
	:global(.rte-strikethrough) { text-decoration: line-through; }
	:global(.rte-code) {
		font-family: monospace;
		background: var(--color-hover);
		padding: 0.1rem 0.3rem;
		border-radius: 3px;
		font-size: 0.85em;
	}

	:global(.rte-h1) { font-size: 1.75rem; font-weight: 700; margin: 0.5rem 0; }
	:global(.rte-h2) { font-size: 1.375rem; font-weight: 700; margin: 0.4rem 0; }
	:global(.rte-h3) { font-size: 1.125rem; font-weight: 700; margin: 0.3rem 0; }

	:global(.rte-ul) { list-style: disc; padding-left: 1.5rem; margin: 0.25rem 0; }
	:global(.rte-ol) { list-style: decimal; padding-left: 1.5rem; margin: 0.25rem 0; }
	:global(.rte-li) { margin: 0.125rem 0; }

	:global(.rte-blockquote) {
		border-left: 3px solid var(--color-border);
		padding-left: 1rem;
		color: var(--color-muted);
		margin: 0.5rem 0;
	}

	:global(.rte-link) {
		color: var(--color-primary);
		text-decoration: underline;
	}
</style>

// apps/admin-v2/src/ui/rich-text-editor.tsx
import { $generateHtmlFromNodes, $generateNodesFromDOM } from '@lexical/html';
import { $isLinkNode, $toggleLink, AutoLinkNode, LinkNode, TOGGLE_LINK_COMMAND } from '@lexical/link';
import { $isListNode, INSERT_ORDERED_LIST_COMMAND, INSERT_UNORDERED_LIST_COMMAND, ListItemNode, ListNode, registerList } from '@lexical/list';
import { $createHeadingNode, $createQuoteNode, $isHeadingNode, $isQuoteNode, HeadingNode, QuoteNode, registerRichText } from '@lexical/rich-text';
import { $setBlocksType } from '@lexical/selection';
import {
	$createParagraphNode,
	$getRoot,
	$getSelection,
	$isRangeSelection,
	$setSelection,
	createEditor,
	FORMAT_TEXT_COMMAND,
	type LexicalEditor,
	type RangeSelection,
} from 'lexical';
import { Show, createEffect, createSignal, onSettled, untrack } from 'solid-js';
import './rich-text-editor.css';

const EXTERNAL_VALUE_TAG = 'admin-external-value';

export type RichTextEditorProps = {
	disabled?: boolean;
	label: string;
	onChange?: (html: string) => void;
	value?: string;
};

export function RichTextEditor(props: RichTextEditorProps) {
	let rootElement: HTMLDivElement | undefined;
	let editor: LexicalEditor | undefined;
	const initialValue = untrack(() => props.value ?? '');
	let lastParentValue = initialValue;
	let lastEmittedValue: string | undefined;
	let lastGeneratedHtml = initialValue;
	let savedLinkSelection: RangeSelection | null = null;
	const [ready, setReady] = createSignal(false);
	const [isBold, setIsBold] = createSignal(false);
	const [isItalic, setIsItalic] = createSignal(false);
	const [isUnderline, setIsUnderline] = createSignal(false);
	const [isStrikethrough, setIsStrikethrough] = createSignal(false);
	const [blockType, setBlockType] = createSignal('paragraph');
	const [linkActive, setLinkActive] = createSignal(false);
	const [linkEditorOpen, setLinkEditorOpen] = createSignal(false);
	const [linkUrl, setLinkUrl] = createSignal('');
	const [linkError, setLinkError] = createSignal('');

	function replaceHtml(instance: LexicalEditor, html: string): void {
		instance.update(
			() => {
				const document = new DOMParser().parseFromString(html, 'text/html');
				const root = $getRoot();
				root.clear();
				root.append(...$generateNodesFromDOM(instance, document));
				lastGeneratedHtml = $generateHtmlFromNodes(instance);
			},
			{ tag: EXTERNAL_VALUE_TAG },
		);
	}

	onSettled(() => {
		if (!rootElement) return;

		const instance = createEditor({
			namespace: 'YahAdminRichText',
			nodes: [HeadingNode, QuoteNode, ListNode, ListItemNode, LinkNode, AutoLinkNode],
			onError: (error) => console.error('[RichTextEditor]', error),
			theme: {
				text: {
					bold: 'rich-text-editor-bold',
					italic: 'rich-text-editor-italic',
					underline: 'rich-text-editor-underline',
					strikethrough: 'rich-text-editor-strikethrough',
				},
				heading: { h1: 'rich-text-editor-h1', h2: 'rich-text-editor-h2', h3: 'rich-text-editor-h3' },
				list: { ul: 'rich-text-editor-ul', ol: 'rich-text-editor-ol', listitem: 'rich-text-editor-li' },
				quote: 'rich-text-editor-quote',
				link: 'rich-text-editor-link',
			},
		});
		editor = instance;
		instance.setRootElement(rootElement);
		instance.setEditable(!props.disabled);
		const unregisterRichText = registerRichText(instance);
		const unregisterList = registerList(instance);

		if (lastParentValue) replaceHtml(instance, lastParentValue);
		const unregisterUpdates = instance.registerUpdateListener(({ editorState, tags }) => {
			// eslint-disable-next-line solid/reactivity -- Lexical invokes this callback inside its own editor-state read scope.
			editorState.read(() => {
				const selection = $getSelection();
				if ($isRangeSelection(selection)) {
					setIsBold(selection.hasFormat('bold'));
					setIsItalic(selection.hasFormat('italic'));
					setIsUnderline(selection.hasFormat('underline'));
					setIsStrikethrough(selection.hasFormat('strikethrough'));
					const anchor = selection.anchor.getNode();
					const element = anchor.getKey() === 'root' ? anchor : anchor.getTopLevelElementOrThrow();
					if ($isHeadingNode(element)) setBlockType(element.getTag());
					else if ($isQuoteNode(element)) setBlockType('quote');
					else if ($isListNode(element)) setBlockType(element.getListType());
					else setBlockType(element.getType());
					setLinkActive($isLinkNode(anchor) || $isLinkNode(anchor.getParent()));
				}
				const html = $generateHtmlFromNodes(instance);
				if (html === lastGeneratedHtml) return;

				lastGeneratedHtml = html;
				if (!tags.has(EXTERNAL_VALUE_TAG) && !untrack(() => props.disabled)) {
					lastEmittedValue = html;
					untrack(() => props.onChange)?.(html);
				}
			});
		});
		setReady(true);

		return () => {
			setReady(false);
			unregisterUpdates();
			unregisterList();
			unregisterRichText();
			instance.setRootElement(null);
			if (editor === instance) editor = undefined;
		};
	});

	createEffect(
		() => ({ disabled: !!props.disabled, ready: ready() }),
		(state) => {
			if (state.ready) editor?.setEditable(!state.disabled);
			if (state.disabled) setLinkEditorOpen(false);
		},
	);

	createEffect(
		() => ({ ready: ready(), value: props.value ?? '' }),
		(state) => {
			if (!state.ready || !editor) return;
			if (state.value === lastEmittedValue) {
				lastParentValue = state.value;
				lastEmittedValue = undefined;
				return;
			}
			if (state.value === lastParentValue) return;

			lastEmittedValue = undefined;
			lastParentValue = state.value;
			replaceHtml(editor, state.value);
		},
	);

	function formatText(format: 'bold' | 'italic' | 'underline' | 'strikethrough'): void {
		if (!ready() || props.disabled || !editor) return;
		editor.dispatchCommand(FORMAT_TEXT_COMMAND, format);
		editor.focus();
	}

	function formatHeading(tag: 'h1' | 'h2' | 'h3'): void {
		if (!ready() || props.disabled || !editor) return;
		const active = blockType() === tag;
		editor.update(() => {
			const selection = $getSelection();
			if ($isRangeSelection(selection)) $setBlocksType(selection, () => active ? $createParagraphNode() : $createHeadingNode(tag));
		});
		editor.focus();
	}

	function formatQuote(): void {
		if (!ready() || props.disabled || !editor) return;
		const active = blockType() === 'quote';
		editor.update(() => {
			const selection = $getSelection();
			if ($isRangeSelection(selection)) $setBlocksType(selection, () => active ? $createParagraphNode() : $createQuoteNode());
		});
		editor.focus();
	}

	function insertList(type: 'bullet' | 'number'): void {
		if (!ready() || props.disabled || !editor) return;
		editor.dispatchCommand(type === 'bullet' ? INSERT_UNORDERED_LIST_COMMAND : INSERT_ORDERED_LIST_COMMAND, undefined);
		editor.focus();
	}

	function editLink(): void {
		if (!ready() || props.disabled || !editor) return;
		if (linkActive()) {
			editor.dispatchCommand(TOGGLE_LINK_COMMAND, null);
			editor.focus();
			return;
		}
		editor.getEditorState().read(() => {
			const selection = $getSelection();
			savedLinkSelection = $isRangeSelection(selection) ? selection.clone() : null;
		});
		setLinkError('');
		setLinkUrl('');
		setLinkEditorOpen(true);
	}

	function normalizedLinkUrl(value: string): string | null {
		const input = value.trim();
		try {
			const url = new URL(input);
			return ['http:', 'https:', 'mailto:'].includes(url.protocol) ? url.toString() : null;
		} catch {
			return null;
		}
	}

	function applyLink(): void {
		if (!editor) return;
		const url = normalizedLinkUrl(linkUrl());
		if (!url) {
			setLinkError('Enter an http, https, or mailto URL.');
			return;
		}
		editor.update(() => {
			if (savedLinkSelection) $setSelection(savedLinkSelection.clone());
			$toggleLink(url);
		});
		savedLinkSelection = null;
		setLinkEditorOpen(false);
		setLinkError('');
		editor.focus();
	}

	return (
		<div class="rich-text-editor">
			<div class="rich-text-editor-toolbar" role="toolbar" aria-label={`${props.label} formatting`} onPointerDown={(event) => { if (event.target instanceof Element && event.target.closest('button')) event.preventDefault(); }}>
				<div class="rich-text-editor-toolbar-group">
					<button type="button" disabled={!ready() || props.disabled} aria-label="Bold" aria-pressed={isBold() ? 'true' : 'false'} onClick={() => formatText('bold')}><strong>B</strong></button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Italic" aria-pressed={isItalic() ? 'true' : 'false'} onClick={() => formatText('italic')}><em>I</em></button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Underline" aria-pressed={isUnderline() ? 'true' : 'false'} onClick={() => formatText('underline')}><u>U</u></button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Strikethrough" aria-pressed={isStrikethrough() ? 'true' : 'false'} onClick={() => formatText('strikethrough')}><s>S</s></button>
				</div>
				<span class="rich-text-editor-toolbar-divider" aria-hidden="true" />
				<div class="rich-text-editor-toolbar-group">
					<button type="button" disabled={!ready() || props.disabled} aria-label="Heading 1" aria-pressed={blockType() === 'h1' ? 'true' : 'false'} onClick={() => formatHeading('h1')}>H1</button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Heading 2" aria-pressed={blockType() === 'h2' ? 'true' : 'false'} onClick={() => formatHeading('h2')}>H2</button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Heading 3" aria-pressed={blockType() === 'h3' ? 'true' : 'false'} onClick={() => formatHeading('h3')}>H3</button>
				</div>
				<span class="rich-text-editor-toolbar-divider" aria-hidden="true" />
				<div class="rich-text-editor-toolbar-group">
					<button type="button" disabled={!ready() || props.disabled} aria-label="Bulleted list" aria-pressed={blockType() === 'bullet' ? 'true' : 'false'} onClick={() => insertList('bullet')}>• List</button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Numbered list" aria-pressed={blockType() === 'number' ? 'true' : 'false'} onClick={() => insertList('number')}>1. List</button>
					<button type="button" disabled={!ready() || props.disabled} aria-label="Block quote" aria-pressed={blockType() === 'quote' ? 'true' : 'false'} onClick={formatQuote}>Quote</button>
				</div>
				<span class="rich-text-editor-toolbar-divider" aria-hidden="true" />
				<button type="button" disabled={!ready() || props.disabled} aria-label={linkActive() ? 'Remove link' : 'Add link'} aria-pressed={linkActive() ? 'true' : 'false'} onClick={editLink}>{linkActive() ? 'Unlink' : 'Link'}</button>
			</div>
			<Show when={linkEditorOpen()}>
				<form class="rich-text-editor-link-form" onSubmit={(event) => { event.preventDefault(); applyLink(); }}>
					<label><span>Link URL</span><input type="url" value={linkUrl()} placeholder="https://example.org" required onInput={(event) => { setLinkUrl(event.currentTarget.value); setLinkError(''); }} /></label>
					<button type="submit">Apply link</button>
					<button type="button" onClick={() => { setLinkEditorOpen(false); setLinkError(''); editor?.focus(); }}>Cancel</button>
					<Show when={linkError()}>{(message) => <span class="field-error" role="alert">{message()}</span>}</Show>
				</form>
			</Show>
			<div
				ref={(element) => {
					rootElement = element;
				}}
				class="rich-text-editor-input"
				role="textbox"
				aria-label={props.label}
				aria-multiline="true"
				aria-disabled={props.disabled ? 'true' : undefined}
				aria-busy={ready() ? undefined : 'true'}
				contenteditable={ready() && !props.disabled}
				spellcheck={true}
			/>
		</div>
	);
}
