// apps/admin/src/routes/admin/members/accept/[id].tsx
import { createResource, Match, Switch } from 'solid-js';
import { useNavigate, useParams } from '@solidjs/router';
import { authClient } from '~/lib/auth-client';
import { LOGO_FILL_ORANGE } from '~/lib/constants';
import { Button, Logo } from '~/components/admin';
import '../../auth.css';

export default function AcceptInvitationPage() {
	const params = useParams<{ id: string }>();
	const navigate = useNavigate();

	const [result] = createResource(
		() => params['id'],
		(id) => authClient.organization.acceptInvitation({ invitationId: id }),
	);

	return (
		<div class="auth-page">
			<div class="auth-container">
				<Logo fill={LOGO_FILL_ORANGE} height={100} />

				<div class="auth-card" style={{ 'text-align': 'center' }}>
					<Switch>
						<Match when={result.loading}>
							<p class="auth-muted">Accepting invitation…</p>
						</Match>
						<Match when={result.error || result()?.error}>
							<h2>Something went wrong</h2>
							<p class="auth-error">
								{result.error instanceof Error
									? result.error.message
									: (result()?.error?.message ?? 'Failed to accept invitation.')}
							</p>
							<Button variant="secondary" onClick={() => navigate('/admin/login')}>
								Go to Login
							</Button>
						</Match>
						<Match when={result()?.data}>
							<h2>Welcome!</h2>
							<p class="auth-muted">You've been added to the organization.</p>
							<Button onClick={() => navigate('/admin')}>Go to Dashboard</Button>
						</Match>
					</Switch>
				</div>
			</div>
		</div>
	);
}

// src/routes/admin/members/accept/[id]/+page.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { goto } from '$app/navigation';
	import { authClient } from '$lib/auth-client';
	import { Button, Logo } from '$lib/components/admin';

	let status = $state<'loading' | 'success' | 'error'>('loading');
	let errorMessage = $state('');

	const invitationId = $derived(page.params.id!);

	$effect(() => {
		if (invitationId) acceptInvitation(invitationId);
	});

	async function acceptInvitation(id: string) {
		try {
			await authClient.organization.acceptInvitation({
				invitationId: id,
			});
			status = 'success';
		} catch (err) {
			status = 'error';
			errorMessage = err instanceof Error ? err.message : 'Failed to accept invitation.';
		}
	}
</script>

<div class="accept-page">
	<div class="accept-container">
		<Logo fill="#ff6f00" height={100} />

		{#if status === 'loading'}
			<p>Accepting invitation...</p>
		{:else if status === 'success'}
			<h2>Welcome!</h2>
			<p>You've been added to Youth Alliance for Housing.</p>
			<Button variant="primary" onclick={() => goto('/admin')}>Go to Dashboard</Button>
		{:else}
			<h2>Something went wrong</h2>
			<p class="error">{errorMessage}</p>
			<Button variant="secondary" onclick={() => goto('/admin/login')}>Go to Login</Button>
		{/if}
	</div>
</div>

<style>
	.accept-page {
		min-height: 100vh;
		background: var(--color-page-bg);
		display: flex;
		align-items: center;
		justify-content: center;
	}

	.accept-container {
		text-align: center;
		max-width: 400px;
		padding: 2rem;
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1rem;
	}

	h2 {
		margin: 0;
		color: var(--color-foreground);
	}

	p {
		color: var(--color-muted);
		margin: 0;
	}

	.error {
		color: var(--color-destructive);
	}
</style>
