// apps/admin/src/routes/admin/(app)/emails/campaigns/index.tsx
import { createAsync, revalidate, type RouteDefinition } from '@solidjs/router';
import { For, Show, createMemo, createSignal } from 'solid-js';
import { createSolidTable, getCoreRowModel, getFilteredRowModel, getFacetedRowModel, getFacetedUniqueValues, createColumnHelper, type ColumnFiltersState } from '@tanstack/solid-table';
import { toast } from 'solid-sonner';
import {
	Badge, Button, AlertDialog, DataTable, PageHeader,
	createSelectColumn, multiSelectFilter, type RowSelectionState,
} from '~/components';
import { requireSession } from '~/routes/admin/session';
import { can } from '~/lib/can';
import { campaignStatusVariant, toastError } from '~/lib/utils';
import { listCampaigns, deleteCampaigns, updateCampaignStatus } from '../campaigns.server';
import './index.css';

export const route: RouteDefinition = {
	preload: () => { void listCampaigns(); },
};

type Campaign = {
	id: number;
	name: string;
	subject: string;
	from_email: string;
	status: string;
	send_at: string | null;
	started_at: string | null;
	to_send: number;
	sent: number;
	views: number;
	clicks: number;
	bounces: number;
	lists: { id: number; name: string }[];
	tags: string[];
	created_at: string;
	updated_at: string;
};

function formatNumber(n: number): string {
	if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
	return String(n);
}

const columnHelper = createColumnHelper<Campaign>();

export default function CampaignsPage() {
	const session = createAsync(() => requireSession());
	const data = createAsync(() => listCampaigns());

	// ─── State ───────────────────────────────────────────────────────────────────

	const [globalFilter, setGlobalFilter] = createSignal('');
	const [columnFilters, setColumnFilters] = createSignal<ColumnFiltersState>([]);
	const [rowSelection, setRowSelection] = createSignal<RowSelectionState>({});
	const [confirmDelete, setConfirmDelete] = createSignal(false);
	const [confirmSend, setConfirmSend] = createSignal(false);
	const [sendTarget, setSendTarget] = createSignal<Campaign | null>(null);

	// ─── Handlers ─────────────────────────────────────────────────────────────────

	async function handleDelete() {
		try {
			await deleteCampaigns(selectedRows().map((c) => c.id));
			toast.success(`${selectedRows().length} campaign${selectedRows().length > 1 ? 's' : ''} deleted.`);
			setRowSelection({});
			await revalidate('listCampaigns');
		} catch (err) {
			toastError(err, 'Failed to delete campaigns.');
		}
	}

	async function handleStatusChange(campaign: Campaign, status: 'running' | 'paused' | 'cancelled' | 'scheduled') {
		try {
			await updateCampaignStatus({ id: campaign.id, status });
			toast.success('Campaign status updated.');
			await revalidate('listCampaigns');
		} catch (err) {
			toastError(err, 'Failed to update status.');
		}
	}

	async function confirmSendCampaign() {
		const target = sendTarget();
		if (!target) return;
		try {
			await updateCampaignStatus({ id: target.id, status: 'running' });
			toast.success(`Campaign "${target.name}" started.`);
			await revalidate('listCampaigns');
		} catch (err) {
			toastError(err, 'Failed to start campaign.');
		}
	}

	// ─── Columns ─────────────────────────────────────────────────────────────────

	const columns = [
		createSelectColumn<Campaign>(),
		columnHelper.accessor('name', {
			header: 'Campaign',
			enableColumnFilter: false,
			cell: (info) => (
				<div class="name-col">
					<a href={`/admin/emails/campaigns/${info.row.original.id}`} class="cell-link">{info.getValue()}</a>
					<span class="subject-text">{info.row.original.subject}</span>
				</div>
			),
		}),
		columnHelper.accessor('status', {
			header: 'Status',
			filterFn: multiSelectFilter,
			cell: (info) => <Badge variant={campaignStatusVariant(info.getValue())}>{info.getValue()}</Badge>,
		}),
		columnHelper.accessor('lists', {
			header: 'Lists',
			enableSorting: false,
			enableColumnFilter: false,
			cell: (info) => {
				const lists = info.getValue();
				return lists.length === 0
					? <span class="cell-muted">—</span>
					: <div class="cell-badges"><For each={lists}>{(list) => <Badge>{list.name}</Badge>}</For></div>;
			},
		}),
		columnHelper.display({
			id: 'stats',
			header: 'Sent / Views / Clicks',
			cell: (info) => {
				const c = info.row.original;
				return (
					<div class="stats-col">
						<span>{formatNumber(c.sent)}</span>
						<span class="stats-sep">/</span>
						<span>{formatNumber(c.views)}</span>
						<span class="stats-sep">/</span>
						<span>{formatNumber(c.clicks)}</span>
					</div>
				);
			},
		}),
		columnHelper.accessor('created_at', {
			header: 'Created',
			enableColumnFilter: false,
			cell: (info) => <span class="cell-date">{new Date(info.getValue()).toLocaleDateString()}</span>,
		}),
		columnHelper.accessor('started_at', {
			header: 'Started',
			enableColumnFilter: false,
			cell: (info) => info.getValue()
				? <span class="cell-date">{new Date(info.getValue()!).toLocaleDateString()}</span>
				: <span class="cell-muted">—</span>,
		}),
		columnHelper.display({
			id: 'ended',
			header: 'Ended',
			cell: (info) => {
				const c = info.row.original;
				return c.status === 'finished'
					? <span class="cell-date">{new Date(c.updated_at).toLocaleDateString()}</span>
					: <span class="cell-muted">—</span>;
			},
		}),
		columnHelper.display({
			id: 'actions',
			header: '',
			cell: (info) => {
				const c = info.row.original;
				return (
					<div class="actions-col">
						<Show when={c.status === 'draft' && can(session(), 'campaign', 'send')}>
							<button class="action-btn send" onClick={() => { setSendTarget(c); setConfirmSend(true); }}>Send</button>
						</Show>
						<Show when={c.status === 'running' && can(session(), 'campaign', 'send')}>
							<button class="action-btn" onClick={() => handleStatusChange(c, 'paused')}>Pause</button>
						</Show>
						<Show when={c.status === 'paused' && can(session(), 'campaign', 'send')}>
							<button class="action-btn send" onClick={() => handleStatusChange(c, 'running')}>Resume</button>
							<button class="action-btn danger" onClick={() => handleStatusChange(c, 'cancelled')}>Cancel</button>
						</Show>
						<Show when={c.status === 'scheduled' && can(session(), 'campaign', 'send')}>
							<button class="action-btn danger" onClick={() => handleStatusChange(c, 'cancelled')}>Cancel</button>
						</Show>
					</div>
				);
			},
		}),
	];

	// ─── Table ───────────────────────────────────────────────────────────────────

	const table = createSolidTable({
		get data() { return (data()?.campaigns ?? []) as Campaign[]; },
		columns,
		state: {
			get globalFilter() { return globalFilter(); },
			get columnFilters() { return columnFilters(); },
			get rowSelection() { return rowSelection(); },
		},
		onGlobalFilterChange: setGlobalFilter,
		onColumnFiltersChange: setColumnFilters,
		onRowSelectionChange: setRowSelection,
		enableRowSelection: (row) =>
			can(session(), 'campaign', 'delete') && row.original.status === 'draft',
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getFacetedRowModel: getFacetedRowModel(),
		getFacetedUniqueValues: getFacetedUniqueValues(),
	});

	const selectedRows = createMemo(() => table.getSelectedRowModel().rows.map((r) => r.original));
	const allSelectedAreDraft = createMemo(() => selectedRows().every((c) => c.status === 'draft'));

	// ─── Toolbar ──────────────────────────────────────────────────────────────────

	const toolbar = () => (
		<Show
			when={selectedRows().length > 0}
			fallback={
				<div class="dt-toolbar-search">
					<input
						class="admin-input"
						type="text"
						placeholder="Search campaigns…"
						value={globalFilter()}
						onInput={(e) => setGlobalFilter(e.currentTarget.value)}
					/>
					<Show when={can(session(), 'campaign', 'create')}>
						<Button href="/admin/emails/campaigns/new">+ New Campaign</Button>
					</Show>
				</div>
			}
		>
			<span class="dt-selection-count">{selectedRows().length} selected</span>
			<Show when={can(session(), 'campaign', 'delete') && allSelectedAreDraft()}>
				<Button variant="danger-outline" onClick={() => setConfirmDelete(true)}>Delete</Button>
			</Show>
			<button class="dt-clear-btn" onClick={() => setRowSelection({})}>Clear</button>
		</Show>
	);

	return (
		<>
			<PageHeader title="Campaigns" />

			<DataTable table={table} toolbar={toolbar} emptyMessage="No campaigns found." />

			<AlertDialog
				open={confirmDelete()}
				onOpenChange={setConfirmDelete}
				title={`Delete Campaign${selectedRows().length > 1 ? 's' : ''}`}
				description={`Permanently delete ${selectedRows().length} draft campaign${selectedRows().length > 1 ? 's' : ''}? This cannot be undone.`}
				confirmLabel="Yes, delete"
				onconfirm={handleDelete}
			/>

			<AlertDialog
				open={confirmSend()}
				onOpenChange={setConfirmSend}
				title="Send Campaign"
				description={`Start sending "${sendTarget()?.name}" to all subscribers on the selected lists? This cannot be undone.`}
				confirmLabel="Yes, send now"
				variant="primary"
				onconfirm={confirmSendCampaign}
			/>
		</>
	);
}

// src/routes/admin/emails/campaigns/+page.svelte
<script lang="ts">
	import { Badge, Button, ConfirmDialog, EmptyState, Input, DataTable } from '$lib/components/admin';
	import { createSvelteTable, renderSnippet, multiSelectFilter, createSelectColumn } from '$lib/components/admin';
	import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getFacetedRowModel, getFacetedUniqueValues, type RowSelectionState, type ColumnFiltersState } from '@tanstack/table-core';
	import { toast } from 'svelte-sonner';
	import { toastError } from '$lib/utils/toast-error';
	import { listCampaigns, deleteCampaigns, updateCampaignStatus } from '../campaigns.remote';
	import { getSession } from '../../session.remote';
	import { can } from '../../can';
	import { campaignStatusVariant } from '$lib/utils/admin';

	let session = $derived(getSession().current);

	// ─── Filters ─────────────────────────────────────────────────────
	let globalFilter = $state('');
	let columnFilters = $state<ColumnFiltersState>([]);

	let data = $derived(await listCampaigns());

	// ─── Row Selection ────────────────────────────────────────────────
	let rowSelection = $state<RowSelectionState>({});
	let selectedRows = $derived.by(() => {
		if (!data) return [];
		return Object.keys(rowSelection)
			.filter((k) => rowSelection[k])
			.map((k) => data.campaigns[Number(k)])
			.filter(Boolean);
	});
	let selectedCount = $derived(selectedRows.length);
	let allSelectedAreDraft = $derived(selectedRows.every((c) => c.status === 'draft'));

	function clearSelection() {
		rowSelection = {};
	}

	// ─── Confirm Dialogs ──────────────────────────────────────────────
	let confirmDelete = $state(false);
	let confirmSend = $state(false);
	let sendTarget = $state<Campaign | null>(null);

	async function handleDelete() {
		try {
			await deleteCampaigns(selectedRows.map((c) => c.id));
			toast.success(`${selectedCount} campaign${selectedCount > 1 ? 's' : ''} deleted.`);
			clearSelection();
			listCampaigns().refresh();
		} catch (err) {
			toastError(err, 'Failed to delete campaign.');
		}
	}

	async function handleSendNow(campaign: Campaign) {
		sendTarget = campaign;
		confirmSend = true;
	}

	async function confirmSendCampaign() {
		if (!sendTarget) return;
		try {
			await updateCampaignStatus({ id: sendTarget.id, status: 'running' });
			toast.success(`Campaign "${sendTarget.name}" started.`);
			listCampaigns().refresh();
		} catch (err) {
			toastError(err, 'Failed to start campaign.');
		}
	}

	async function handleStatusChange(campaign: Campaign, status: 'running' | 'paused' | 'cancelled' | 'scheduled') {
		try {
			await updateCampaignStatus({ id: campaign.id, status });
			toast.success(`Campaign status updated.`);
			listCampaigns().refresh();
		} catch (err) {
			toastError(err, 'Failed to update status.');
		}
	}

	function formatNumber(n: number): string {
		if (n >= 1000) return `${(n / 1000).toFixed(1)}k`;
		return String(n);
	}

	type Campaign = {
		id: number;
		name: string;
		subject: string;
		from_email: string;
		status: string;
		send_at: string | null;
		started_at: string | null;
		to_send: number;
		sent: number;
		views: number;
		clicks: number;
		bounces: number;
		lists: { id: number; name: string }[];
		tags: string[];
		created_at: string;
		updated_at: string;
	};

	const columnHelper = createColumnHelper<Campaign>();

	const columns = [
		createSelectColumn<Campaign>(),
		columnHelper.accessor('name', {
			header: 'Campaign',
			cell: (info) => renderSnippet(nameCell, info.row.original),
			enableColumnFilter: false,
		}),
		columnHelper.accessor('status', {
			header: 'Status',
			cell: (info) => renderSnippet(statusCell, info.row.original),
			enableColumnFilter: true,
			filterFn: multiSelectFilter,
		}),
		columnHelper.accessor('lists', {
			header: 'Lists',
			cell: (info) => renderSnippet(listsCell, info.getValue()),
			enableSorting: false,
			enableColumnFilter: false,
		}),
		columnHelper.display({
			id: 'stats',
			header: 'Sent / Views / Clicks',
			cell: (info) => renderSnippet(statsCell, info.row.original),
			enableSorting: false,
			enableColumnFilter: false,
		}),
		columnHelper.accessor('created_at', {
			header: 'Created',
			cell: (info) => renderSnippet(dateCell, info.getValue()),
			enableColumnFilter: false,
		}),
		columnHelper.accessor('started_at', {
			header: 'Started',
			cell: (info) => renderSnippet(optionalDateCell, info.getValue()),
			enableColumnFilter: false,
		}),
		columnHelper.display({
			id: 'ended',
			header: 'Ended',
			cell: (info) => renderSnippet(optionalDateCell, info.row.original.status === 'finished' ? info.row.original.updated_at : null),
			enableColumnFilter: false,
		}),
		columnHelper.display({
			id: 'actions',
			header: '',
			cell: (info) => renderSnippet(actionsCell, info.row.original),
			enableSorting: false,
			enableColumnFilter: false,
		}),
	];
</script>

{#snippet nameCell(campaign: Campaign)}
	<div class="name-col">
		<a href="/admin/emails/campaigns/{campaign.id}" class="cell-link">{campaign.name}</a>
		<span class="subject-text">{campaign.subject}</span>
	</div>
{/snippet}

{#snippet statusCell(campaign: Campaign)}
	<Badge variant={campaignStatusVariant(campaign.status)}>{campaign.status}</Badge>
{/snippet}

{#snippet listsCell(lists: { id: number; name: string }[])}
	<div class="cell-badges">
		{#each lists as list}
			<Badge>{list.name}</Badge>
		{/each}
		{#if lists.length === 0}
			<span class="cell-muted">—</span>
		{/if}
	</div>
{/snippet}

{#snippet statsCell(campaign: Campaign)}
	<div class="stats-col">
		<span>{formatNumber(campaign.sent)}</span>
		<span class="stats-sep">/</span>
		<span>{formatNumber(campaign.views)}</span>
		<span class="stats-sep">/</span>
		<span>{formatNumber(campaign.clicks)}</span>
	</div>
{/snippet}

{#snippet dateCell(date: string)}
	<span class="cell-date">{new Date(date).toLocaleDateString()}</span>
{/snippet}

{#snippet optionalDateCell(date: string | null)}
	{#if date}
		<span class="cell-date">{new Date(date).toLocaleDateString()}</span>
	{:else}
		<span class="cell-muted">—</span>
	{/if}
{/snippet}

{#snippet actionsCell(campaign: Campaign)}
	<div class="actions-col">
		{#if campaign.status === 'draft' && can(session, 'campaign', 'send')}
			<button class="action-btn send" onclick={() => handleSendNow(campaign)} title="Send now">Send</button>
		{/if}
		{#if campaign.status === 'running' && can(session, 'campaign', 'send')}
			<button class="action-btn" onclick={() => handleStatusChange(campaign, 'paused')} title="Pause">Pause</button>
		{/if}
		{#if campaign.status === 'paused' && can(session, 'campaign', 'send')}
			<button class="action-btn send" onclick={() => handleStatusChange(campaign, 'running')} title="Resume">Resume</button>
			<button class="action-btn danger" onclick={() => handleStatusChange(campaign, 'cancelled')} title="Cancel">Cancel</button>
		{/if}
		{#if campaign.status === 'scheduled' && can(session, 'campaign', 'send')}
			<button class="action-btn danger" onclick={() => handleStatusChange(campaign, 'cancelled')} title="Cancel">Cancel</button>
		{/if}
	</div>
{/snippet}

<h1>Campaigns</h1>

{#if data}
	{#snippet toolbar()}
		{#if selectedCount > 0 && can(session, 'campaign', 'delete') && allSelectedAreDraft}
			<span class="toolbar-count">{selectedCount} selected</span>
			<div class="toolbar-actions">
				<Button variant="danger-outline" onclick={() => (confirmDelete = true)}>Delete</Button>
				<button class="toolbar-clear" onclick={clearSelection}>Clear</button>
			</div>
		{:else if selectedCount > 0}
			<span class="toolbar-count">{selectedCount} selected</span>
			<div class="toolbar-actions">
				<button class="toolbar-clear" onclick={clearSelection}>Clear</button>
			</div>
		{:else}
			<div class="toolbar-filters">
				<Input type="text" placeholder="Search campaigns..." bind:value={globalFilter} />
			</div>
			{#if can(session, 'campaign', 'create')}
				<Button variant="primary" href="/admin/emails/campaigns/new">+ New Campaign</Button>
			{/if}
		{/if}
	{/snippet}

	{@const table = createSvelteTable({
		data: data.campaigns,
		columns,
		state: { rowSelection, columnFilters, globalFilter },
		onRowSelectionChange: (updater) => {
			rowSelection = typeof updater === 'function' ? updater(rowSelection) : updater;
		},
		onColumnFiltersChange: (updater) => {
			columnFilters = typeof updater === 'function' ? updater(columnFilters) : updater;
		},
		onGlobalFilterChange: (updater) => {
			globalFilter = typeof updater === 'function' ? updater(globalFilter) : updater;
		},
		enableColumnFilters: true,
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getFacetedRowModel: getFacetedRowModel(),
		getFacetedUniqueValues: getFacetedUniqueValues(),
	})}
	<DataTable {table} {toolbar} pageSize={20} />
	{#if data.campaigns.length === 0}
		<EmptyState message="No campaigns found." />
	{/if}
{/if}

<ConfirmDialog
	bind:open={confirmDelete}
	title="Delete Campaign{selectedCount > 1 ? 's' : ''}"
	description="Permanently delete {selectedCount} draft campaign{selectedCount > 1 ? 's' : ''}? This cannot be undone."
	confirmLabel="Yes, delete"
	onconfirm={handleDelete}
/>

<ConfirmDialog
	bind:open={confirmSend}
	title="Send Campaign"
	description="Start sending &quot;{sendTarget?.name}&quot; to all subscribers on the selected lists? This cannot be undone."
	confirmLabel="Yes, send now"
	variant="primary"
	onconfirm={confirmSendCampaign}
/>

<style>
	.name-col {
		display: flex;
		flex-direction: column;
		gap: 0.125rem;
	}

	.subject-text {
		font-size: 0.8rem;
		color: var(--color-muted);
	}

	.stats-col {
		display: flex;
		gap: 0.125rem;
		font-size: 0.85rem;
		font-variant-numeric: tabular-nums;
	}

	.stats-sep {
		color: var(--color-muted);
	}

	.actions-col {
		display: flex;
		gap: 0.375rem;
	}

	.action-btn {
		background: none;
		border: 1px solid var(--color-border);
		border-radius: var(--radius-sm);
		cursor: pointer;
		color: var(--color-muted);
		font-size: 0.75rem;
		padding: 0.2rem 0.5rem;
	}

	.action-btn:hover {
		color: var(--color-foreground);
		background: var(--color-hover);
	}

	.action-btn.send {
		color: var(--color-primary);
		border-color: var(--color-primary);
	}

	.action-btn.send:hover {
		background: color-mix(in srgb, var(--color-primary) 10%, transparent);
	}

	.action-btn.danger {
		color: var(--brand-magenta);
		border-color: var(--brand-magenta);
	}

	.action-btn.danger:hover {
		background: color-mix(in srgb, var(--brand-magenta) 10%, transparent);
	}

	.toolbar-filters {
		display: flex;
		gap: 0.5rem;
		flex: 1;
	}
</style>
