// apps/admin/src/routes/(app)/shortlinks/index.tsx
import { createAsync, revalidate, type RouteDefinition, useNavigate } from '@solidjs/router';
import { For, Show, batch, createMemo, createSignal } from 'solid-js';
import { createSolidTable, getCoreRowModel, getFilteredRowModel, getSortedRowModel, createColumnHelper, type SortingState } from '@tanstack/solid-table';
import { toast } from 'solid-sonner';
import * as v from 'valibot';
import {
	Badge, Button, Input, Switch, FormField,
	AlertDialog, Dialog, DataTable, PageHeader, TagInput,
	createSelectColumn, type RowSelectionState,
} from '~/components';
import { requireSession } from '~/routes/session';
import { can } from '~/lib/can';
import { toastError } from '~/lib/utils';
import { createForm } from '~/lib/use-form';
import {
	listShortUrls, createShortUrl, deleteShortUrl,
} from '../shortlinks.server';
import type { ShortUrl } from '~/server/shlink';
import './index.css';

export const route: RouteDefinition = {
	preload: () => { void listShortUrls(); },
};

const columnHelper = createColumnHelper<ShortUrl>();

// ─── Form schema ──────────────────────────────────────────────────────────────

const CreateSchema = v.object({
	longUrl: v.pipe(v.string(), v.nonEmpty('Destination URL is required'), v.url('Must be a valid URL')),
	slug: v.string(),
	title: v.string(),
	tags: v.array(v.string()),
	maxVisits: v.string(),
	validUntil: v.string(),
	crawlable: v.boolean(),
	forwardQuery: v.boolean(),
});

type CreateValues = v.InferOutput<typeof CreateSchema>;

const initialValues: CreateValues = {
	longUrl: '',
	slug: '',
	title: '',
	tags: [],
	maxVisits: '',
	validUntil: '',
	crawlable: false,
	forwardQuery: true,
};

export default function ShortlinksPage() {
	const navigate = useNavigate();
	const session = createAsync(() => requireSession());
	const urls = createAsync(() => listShortUrls());

	// ─── Table state ────────────────────────────────────────────────────────────

	const [globalFilter, setGlobalFilter] = createSignal('');
	const [rowSelection, setRowSelection] = createSignal<RowSelectionState>({});
	const [sorting, setSorting] = createSignal<SortingState>([{ id: 'dateCreated', desc: true }]);

	// ─── Dialog state ────────────────────────────────────────────────────────────

	const [createOpen, setCreateOpen] = createSignal(false);
	const [confirmDelete, setConfirmDelete] = createSignal(false);
	const [createPending, setCreatePending] = createSignal(false);

	// ─── Create form ──────────────────────────────────────────────────────────────

	const form = createForm(CreateSchema, initialValues);

	// ─── Permissions ─────────────────────────────────────────────────────────────

	const canCreate = createMemo(() => can(session(), 'shortlink', 'create'));
	const canDelete = createMemo(() => can(session(), 'shortlink', 'delete'));

	// ─── Table ───────────────────────────────────────────────────────────────────

	const columns = [
		createSelectColumn<ShortUrl>(),
		columnHelper.accessor('shortCode', {
			header: 'Short URL',
			enableSorting: true,
			cell: (info) => (
				<span>
					<a href={`/shortlinks/${info.getValue()}`} class="code">{info.getValue()}</a>
					<Show when={info.row.original.title}>
						<><br /><span class="row-title">{info.row.original.title}</span></>
					</Show>
				</span>
			),
		}),
		columnHelper.accessor('longUrl', {
			header: 'Destination',
			enableSorting: true,
			cell: (info) => <span class="long-url" title={info.getValue()}>{info.getValue()}</span>,
		}),
		columnHelper.accessor('tags', {
			header: 'Tags',
			enableSorting: false,
			cell: (info) => (
				<div class="cell-badges">
					<For each={info.getValue()}>{(tag) => <Badge>{tag}</Badge>}</For>
				</div>
			),
		}),
		columnHelper.accessor((row) => row.visitsSummary.total, {
			id: 'visits',
			header: 'Clicks',
			enableSorting: true,
			cell: (info) => <span class="clicks">{info.getValue()}</span>,
		}),
		columnHelper.accessor('dateCreated', {
			id: 'dateCreated',
			header: 'Created',
			enableSorting: true,
			cell: (info) => <span class="cell-date">{new Date(info.getValue()).toLocaleDateString()}</span>,
		}),
	];

	const table = createSolidTable({
		get data() { return urls() ?? []; },
		columns,
		state: {
			get globalFilter() { return globalFilter(); },
			get rowSelection() { return rowSelection(); },
			get sorting() { return sorting(); },
		},
		onGlobalFilterChange: setGlobalFilter,
		onRowSelectionChange: setRowSelection,
		onSortingChange: setSorting,
		globalFilterFn: (row, _colId, filterValue: string) => {
			const s = filterValue.toLowerCase();
			return (
				row.original.shortCode.toLowerCase().includes(s) ||
				row.original.longUrl.toLowerCase().includes(s) ||
				(row.original.title?.toLowerCase().includes(s) ?? false) ||
				row.original.tags.some((t) => t.toLowerCase().includes(s))
			);
		},
		enableRowSelection: () => canDelete(),
		enableColumnFilters: false,
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getSortedRowModel: getSortedRowModel(),
	});

	const selectedRows = createMemo(() => table.getSelectedRowModel().rows.map((r) => r.original));

	// ─── Handlers ─────────────────────────────────────────────────────────────────

	const handleCreate = form.handleSubmit(async (values) => {
		setCreatePending(true);
		try {
			const result = await createShortUrl({
				longUrl: values.longUrl,
				customSlug: values.slug || undefined,
				title: values.title || undefined,
				tags: values.tags,
				maxVisits: values.maxVisits ? parseInt(values.maxVisits, 10) || null : null,
				validUntil: values.validUntil || undefined,
				crawlable: values.crawlable,
				forwardQuery: values.forwardQuery,
			});
			batch(() => {
				setCreateOpen(false);
				form.reset();
			});
			toast.success('Shortlink created.');
			navigate(`/shortlinks/${result.shortCode}`);
		} catch (err) {
			toastError(err, 'Failed to create shortlink.');
		} finally {
			setCreatePending(false);
		}
	});

	async function handleDelete() {
		const rows = selectedRows();
		try {
			await Promise.all(rows.map((url) => deleteShortUrl(url.shortCode)));
			toast.success(`${rows.length} shortlink${rows.length > 1 ? 's' : ''} deleted.`);
			setRowSelection({});
			await revalidate('listShortUrls');
		} catch (err) {
			toastError(err, 'Failed to delete shortlinks.');
		}
	}

	// ─── Toolbar ──────────────────────────────────────────────────────────────────

	const toolbar = () => (
		<Show
			when={selectedRows().length > 0}
			fallback={
				<div class="dt-toolbar-search">
					<input
						class="admin-input"
						type="text"
						placeholder="Filter shortlinks…"
						value={globalFilter()}
						onInput={(e) => setGlobalFilter(e.currentTarget.value)}
					/>
					<Show when={canCreate()}>
						<Button onClick={() => { form.reset(); setCreateOpen(true); }}>+ New Shortlink</Button>
					</Show>
				</div>
			}
		>
			<span class="dt-selection-count">{selectedRows().length} selected</span>
			<Button variant="danger-outline" onClick={() => setConfirmDelete(true)}>Delete</Button>
			<button class="dt-clear-btn" onClick={() => setRowSelection({})}>Clear</button>
		</Show>
	);

	return (
		<>
			<PageHeader title="Shortlinks" />

			<DataTable table={table} toolbar={toolbar} />

			<AlertDialog
				open={confirmDelete()}
				onOpenChange={setConfirmDelete}
				title={`Delete Shortlink${selectedRows().length > 1 ? 's' : ''}`}
				description={`Permanently delete ${selectedRows().length} shortlink${selectedRows().length > 1 ? 's' : ''}? This cannot be undone.`}
				confirmLabel="Yes, delete"
				onconfirm={handleDelete}
			/>

			<Show when={canCreate()}>
				<Dialog
					open={createOpen()}
					onOpenChange={(open) => batch(() => { if (!open) form.reset(); setCreateOpen(open); })}
					title="New Shortlink"
					maxWidth="520px"
					footer={<>
						<Button variant="ghost" onClick={() => setCreateOpen(false)}>Cancel</Button>
						<Button onClick={handleCreate} disabled={createPending()}>
							{createPending() ? 'Creating…' : 'Create Shortlink'}
						</Button>
					</>}
				>
					<div class="form-fields">
						<FormField label="Destination URL" required error={form.fieldError('longUrl')}>
							<Input type="url" placeholder="https://example.com/long/path" {...form.field('longUrl')} />
						</FormField>

						<FormField label="Custom Slug" hint="Optional — leave blank for auto-generated">
							<Input placeholder="my-link" {...form.field('slug')} />
						</FormField>

						<FormField label="Title" hint="Optional">
							<Input placeholder="Descriptive title" {...form.field('title')} />
						</FormField>

						<FormField label="Tags" hint="Press Enter to add">
							<TagInput
								tags={form.values.tags}
								onChange={(tags) => form.setValue('tags', tags)}
								placeholder="Add a tag…"
							/>
						</FormField>

						<div class="form-row">
							<FormField label="Max Visits" hint="Optional">
								<Input type="number" placeholder="Unlimited" {...form.field('maxVisits')} />
							</FormField>
							<FormField label="Expires" hint="Optional">
								<Input type="date" {...form.field('validUntil')} />
							</FormField>
						</div>

						<div class="switches">
							<Switch
								label="Forward query parameters"
								checked={form.values.forwardQuery}
								onChange={(v) => form.setValue('forwardQuery', v)}
							/>
							<Switch
								label="Allow search engine crawling"
								checked={form.values.crawlable}
								onChange={(v) => form.setValue('crawlable', v)}
							/>
						</div>

					</div>
				</Dialog>
			</Show>
		</>
	);
}

// src/routes/admin/shortlinks/+page.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button, Input, Badge, Tooltip, FormField, Switch, EmptyState, DataTable, ConfirmDialog, DialogShell, DatePicker, TagInput } from '$lib/components/admin';
	import { createSvelteTable, renderSnippet, createSelectColumn } from '$lib/components/admin';
	import { createColumnHelper, getCoreRowModel, getFilteredRowModel, getSortedRowModel, type SortingState, type RowSelectionState } from '@tanstack/table-core';
	import { today, getLocalTimeZone } from '@internationalized/date';
	import { toast } from 'svelte-sonner';
	import { toastError } from '$lib/utils/toast-error';
	import { listShortUrls, createShortUrl, deleteShortUrl } from '../shortlinks.remote';
	import { getSession } from '../session.remote';
	import { can } from '../can';
	let [session, shortlinksData] = $derived(await Promise.all([getSession(), listShortUrls()]));

	let globalFilter = $state('');
	let sorting = $state<SortingState>([{ id: 'dateCreated', desc: true }]);
	let rowSelection = $state<RowSelectionState>({});

	let createOpen = $state(false);
	let createPending = $state(false);
	let createTags = $state<string[]>([]);
	let confirmDelete = $state(false);

	let selectedRows = $derived.by(() => {
		if (!shortlinksData) return [];
		return Object.keys(rowSelection)
			.filter((k) => rowSelection[k])
			.map((k) => shortlinksData.shortUrls[Number(k)])
			.filter(Boolean);
	});
	let selectedCount = $derived(selectedRows.length);

	function clearSelection() {
		rowSelection = {};
	}

	async function handleDelete() {
		try {
			await Promise.all(selectedRows.map((url) => deleteShortUrl(url.shortCode)));
			toast.success(`${selectedCount} shortlink${selectedCount > 1 ? 's' : ''} deleted.`);
			clearSelection();
			listShortUrls().refresh();
		} catch (err) {
			toastError(err, 'Failed to delete shortlink.');
		}
	}

	async function handleCreate(e: SubmitEvent) {
		e.preventDefault();
		const form = e.target as HTMLFormElement;
		const fd = new FormData(form);

		createPending = true;
		try {
			const result = await createShortUrl({
				longUrl: fd.get('longUrl') as string,
				customSlug: fd.get('customSlug') as string,
				title: fd.get('title') as string,
				tags: createTags.join(', '),
				maxVisits: fd.get('maxVisits') as string,
				validUntil: fd.get('validUntil') as string,
				crawlable: fd.has('crawlable'),
				forwardQuery: fd.has('forwardQuery'),
			});
			createOpen = false;
			toast.success('Shortlink created.');
			goto(`/admin/shortlinks/${result.shortCode}`);
		} catch (err) {
			toastError(err, 'Failed to create shortlink.');
		} finally {
			createPending = false;
		}
	}

	type ShortUrl = {
		shortCode: string;
		longUrl: string;
		title?: string | null;
		tags: string[];
		visitsSummary: { total: number };
		dateCreated: string;
	};

	const columnHelper = createColumnHelper<ShortUrl>();

	const columns = [
		createSelectColumn<ShortUrl>(),
		columnHelper.accessor('shortCode', {
			header: 'Short URL',
			cell: (info) => renderSnippet(shortCodeCell, info.row.original),
			enableSorting: true,
			enableColumnFilter: false,
		}),
		columnHelper.accessor('longUrl', {
			header: 'Destination',
			cell: (info) => renderSnippet(longUrlCell, info.getValue()),
			enableSorting: true,
			enableColumnFilter: false,
		}),
		columnHelper.accessor('tags', {
			header: 'Tags',
			cell: (info) => renderSnippet(tagsCell, info.getValue()),
			enableSorting: false,
			enableColumnFilter: false,
		}),
		columnHelper.accessor((row) => row.visitsSummary.total, {
			id: 'visits',
			header: 'Clicks',
			cell: (info) => renderSnippet(clicksCell, info.getValue()),
			enableSorting: true,
			enableColumnFilter: false,
		}),
		columnHelper.accessor('dateCreated', {
			header: 'Created',
			cell: (info) => renderSnippet(dateCell, info.getValue()),
			enableSorting: true,
			enableColumnFilter: false,
		}),
	];
</script>

{#snippet shortCodeCell(url: ShortUrl)}
	<a href="/admin/shortlinks/{url.shortCode}" class="code">{url.shortCode}</a>
	{#if url.title}<br /><span class="title">{url.title}</span>{/if}
{/snippet}

{#snippet longUrlCell(longUrl: string)}
	<span class="long-url"><Tooltip text={longUrl}>{longUrl}</Tooltip></span>
{/snippet}

{#snippet tagsCell(tags: string[])}
	<div class="tags">
		{#each tags as tag}
			<Badge>{tag}</Badge>
		{/each}
	</div>
{/snippet}

{#snippet clicksCell(total: number)}
	<span class="clicks">{total}</span>
{/snippet}

{#snippet dateCell(date: string)}
	<span class="cell-date">{new Date(date).toLocaleDateString()}</span>
{/snippet}

<h1>Shortlinks</h1>

{#if shortlinksData}
	{#snippet toolbar()}
		{#if selectedCount > 0 && can(session, 'shortlink', 'delete')}
			<span class="toolbar-count">{selectedCount} selected</span>
			<div class="toolbar-actions">
				<Button variant="danger-outline" onclick={() => (confirmDelete = true)}>Delete</Button>
				<button class="toolbar-clear" onclick={clearSelection}>Clear</button>
			</div>
		{:else}
			<div class="toolbar-search">
				<Input type="text" placeholder="Filter shortlinks..." bind:value={globalFilter} />
			</div>
			{#if can(session, 'shortlink', 'create')}
				<Button variant="primary" onclick={() => { createTags = []; createOpen = true; }}>+ New Shortlink</Button>
			{/if}
		{/if}
	{/snippet}

	{@const table = createSvelteTable({
		data: shortlinksData.shortUrls,
		columns,
		state: { sorting, rowSelection, globalFilter },
		onSortingChange: (updater) => {
			sorting = typeof updater === 'function' ? updater(sorting) : updater;
		},
		onRowSelectionChange: (updater) => {
			rowSelection = typeof updater === 'function' ? updater(rowSelection) : updater;
		},
		onGlobalFilterChange: (updater) => {
			globalFilter = typeof updater === 'function' ? updater(globalFilter) : updater;
		},
		getCoreRowModel: getCoreRowModel(),
		getFilteredRowModel: getFilteredRowModel(),
		getSortedRowModel: getSortedRowModel(),
	})}

	<DataTable {table} {toolbar} />

	{#if shortlinksData.shortUrls.length === 0}
		<EmptyState message="No shortlinks found." />
	{/if}
{/if}

<ConfirmDialog
	bind:open={confirmDelete}
	title="Delete Shortlink{selectedCount > 1 ? 's' : ''}"
	description="Permanently delete {selectedCount} shortlink{selectedCount > 1 ? 's' : ''}? This cannot be undone."
	confirmLabel="Yes, delete"
	onconfirm={handleDelete}
/>

{#if can(session, 'shortlink', 'create')}
<!-- Create Shortlink Dialog -->
<DialogShell bind:open={createOpen} title="New Shortlink" maxWidth="520px">
	<form class="form-fields" onsubmit={handleCreate}>
		<FormField label="Destination URL" required>
			<Input name="longUrl" type="url" required placeholder="https://example.com/long/path" />
		</FormField>

		<FormField label="Custom Slug" hint="(optional — leave blank for auto-generated)">
			<Input name="customSlug" placeholder="my-link" />
		</FormField>

		<FormField label="Title" hint="(optional)">
			<Input name="title" placeholder="Descriptive title" />
		</FormField>

		<FormField label="Tags" hint="Press Enter to add">
			<TagInput bind:tags={createTags} placeholder="Add a tag..." />
		</FormField>

		<div class="form-row">
			<FormField label="Max Visits" hint="(optional)">
				<Input name="maxVisits" placeholder="Unlimited" />
			</FormField>

			<FormField label="Expires" hint="(optional)">
				<DatePicker name="validUntil" minValue={today(getLocalTimeZone())} />
			</FormField>
		</div>

		<div class="switches">
			<Switch label="Forward query parameters" checked={true} name="forwardQuery" />
			<Switch label="Allow search engine crawling" checked={false} name="crawlable" />
		</div>

		<div class="dialog-actions">
			<Button variant="ghost" onclick={() => (createOpen = false)}>Cancel</Button>
			<Button variant="primary" type="submit" disabled={createPending}>
				{createPending ? 'Creating...' : 'Create Shortlink'}
			</Button>
		</div>
	</form>
</DialogShell>
{/if}

<style>
	.code {
		font-family: monospace;
		color: var(--color-primary);
		text-decoration: none;
		font-weight: 600;
	}

	.code:hover {
		text-decoration: underline;
	}

	.title {
		font-size: 0.8rem;
		color: var(--color-muted);
	}

	.long-url {
		display: block;
		max-width: 300px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		color: var(--color-muted);
	}

	.tags {
		display: flex;
		flex-wrap: wrap;
		gap: 0.25rem;
	}

	.clicks {
		font-weight: 600;
		color: var(--brand-amber-dark);
	}

	.switches {
		display: flex;
		flex-direction: column;
		gap: 0.75rem;
	}
</style>
